import { useMemo, useState } from 'react';
import { Head, router } from '@inertiajs/react';
import { Books, Buildings, CalendarBlank, ChartBar, CheckSquare, GearSix, Lightning, MapTrifold, Trophy, UsersThree } from '@phosphor-icons/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent } from '@/Components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/Components/ui/dialog';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/Components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/Components/ui/tabs';

type Id=string;
type Ready='ready'|'attention'|'decision'|'closed';
type Material={id?:Id;name?:string;code?:string};
type Line={id:Id;repeticoes:number;distancia_m:number;exercicio?:string|null;zona?:string|null;training_zone_config_id?:Id|null;estilo?:string|null;sports_stroke_id?:Id|null;intervalo?:string|null;saida?:string|null;timing_mode:'none'|'each_rep'|'whole_series';material:Material[];observacoes?:string|null;source?:string|null};
type Block={name:string;order:number;rounds:number;series:Line[]};
type Group={id:Id;group_id:Id;group_name?:string|null;instruction?:string|null;plan?:{id:Id;name?:string|null;version:number;latest_version?:number|null}|null;lanes:Array<{id:Id;number?:number|null;name?:string|null}>};
type Session={id:Id;number?:string|null;date:string;start_time?:string|null;end_time?:string|null;status:string;training_type?:string|null;volume_m:number;description?:string|null;notes?:string|null;readiness:{status:Ready;checks:Array<{key:string;status:string;label:string;message:string}>};periodization:{season_id?:Id|null;season?:string|null;macro?:string|null;meso?:string|null;micro?:string|null};coach?:{id:Id;name:string}|null;location:{venue?:string|null;pool?:string|null;pool_length_m?:string|number|null};plan?:{id:Id;name?:string|null;version:number;latest?:{id:Id;version:number;name?:string|null}|null}|null;content_overridden:boolean;content_override?:{at?:string|null;by?:string|null;reason?:string|null}|null;blocks:Block[];groups:Group[];athletes:Array<{id:Id;name:string}>;cancellation?:{at?:string|null;by?:string|null;reason?:string|null}|null;history:Array<{type:string;at?:string|null;title:string;detail?:string|null;by?:string|null}>};
type Props={activeSeason?:{id:Id;name:string;year:string}|null;seasons:Array<{id:Id;name:string;year:string;status:string}>;sessions:Session[];stats:{today:number;attention:number;decisions:number;next7days:number}};
type EditLine={key:string;repeticoes:string;distancia_m:string;exercicio:string;intervalo:string;saida:string;timing_mode:'none'|'each_rep'|'whole_series';training_zone_config_id:string;sports_stroke_id:string;zona_intensidade:string;estilo:string;material:Material[];observacoes:string};
type EditBlock={key:string;name:string;rounds:string;series:EditLine[]};

const nav=[
 ['dashboard','Dashboard',ChartBar,()=>route('desportivo.index')],['atletas','Atletas',UsersThree,()=>route('desportivo.index',{tab:'atletas'})],['planeamento','Planeamento',MapTrifold,()=>route('desportivo.planeamento')],['biblioteca','Biblioteca',Books,()=>route('desportivo.biblioteca')],['treinos','Treinos',CalendarBlank,()=>route('desportivo.treinos')],['cais','Cais',CheckSquare,()=>route('desportivo.cais')],['competicoes','Competições',Trophy,()=>route('desportivo.competicoes')],['performance','Performance',Lightning,()=>route('desportivo.relatorios')],
] as const;
const statusLabel=(v:string)=>({draft:'Rascunho',published:'Publicado',completed:'Concluído',cancelled:'Cancelado'}[v]??v);
const readyLabel=(v:Ready)=>({ready:'Pronto',attention:'Atenção',decision:'Decisão necessária',closed:'Fechado'}[v]);
const readyVariant=(v:Ready):'default'|'secondary'|'outline'|'destructive'=>v==='decision'?'destructive':v==='ready'?'default':v==='closed'?'secondary':'outline';
const dateLabel=(v:string)=>new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${v}T12:00:00`));
const timeRange=(s:Session)=>[s.start_time,s.end_time].filter(Boolean).join('–')||'Sem horário';
const toEdit=(blocks:Block[]):EditBlock[]=>blocks.map((b,bi)=>({key:`b-${bi}-${crypto.randomUUID()}`,name:b.name,rounds:String(b.rounds||1),series:b.series.map((l,li)=>({key:`l-${li}-${crypto.randomUUID()}`,repeticoes:String(l.repeticoes||1),distancia_m:String(l.distancia_m||''),exercicio:l.exercicio??'',intervalo:l.intervalo??'',saida:l.saida??'',timing_mode:l.timing_mode||'none',training_zone_config_id:l.training_zone_config_id??'',sports_stroke_id:l.sports_stroke_id??'',zona_intensidade:l.zona??'',estilo:l.estilo??'',material:l.material??[],observacoes:l.observacoes??''}))}));

export default function TrainingWorkspace({activeSeason,seasons,sessions,stats}:Props){
 const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [ready,setReady]=useState('all'); const [group,setGroup]=useState('all'); const [coach,setCoach]=useState('all'); const [view,setView]=useState<'list'|'cards'>('list');
 const [selectedId,setSelectedId]=useState<Id|null>(null); const [tab,setTab]=useState('summary'); const [cancelOpen,setCancelOpen]=useState(false); const [cancelReason,setCancelReason]=useState(''); const [adaptOpen,setAdaptOpen]=useState(false); const [adaptReason,setAdaptReason]=useState(''); const [editBlocks,setEditBlocks]=useState<EditBlock[]>([]);
 const selected=selectedId?sessions.find(s=>s.id===selectedId)??null:null;
 const groups=useMemo(()=>Array.from(new Set(sessions.flatMap(s=>s.groups.map(g=>g.group_name).filter(Boolean) as string[]))).sort(),[sessions]);
 const coaches=useMemo(()=>Array.from(new Set(sessions.map(s=>s.coach?.name).filter(Boolean) as string[])).sort(),[sessions]);
 const filtered=useMemo(()=>sessions.filter(s=>{
   if(status!=='all'&&s.status!==status)return false; if(ready!=='all'&&s.readiness.status!==ready)return false; if(group!=='all'&&!s.groups.some(g=>g.group_name===group))return false; if(coach!=='all'&&s.coach?.name!==coach)return false;
   const q=query.trim().toLocaleLowerCase('pt-PT'); if(!q)return true; return [s.number,s.training_type,s.plan?.name,s.coach?.name,s.location.venue,s.location.pool,...s.groups.map(g=>g.group_name),...s.athletes.map(a=>a.name)].filter(Boolean).join(' ').toLocaleLowerCase('pt-PT').includes(q);
 }).sort((a,b)=>{const ac=['completed','cancelled'].includes(a.status),bc=['completed','cancelled'].includes(b.status);return ac!==bc?(ac?1:-1):`${a.date} ${a.start_time??''}`.localeCompare(`${b.date} ${b.start_time??''}`)}),[sessions,query,status,ready,group,coach]);
 const goPlanning=(s?:Session|null)=>router.get(route('desportivo.planeamento',s?{season_id:s.periodization.season_id,training_id:s.id}:{season_id:activeSeason?.id}));
 const goCais=(s:Session)=>router.get(route('desportivo.cais',{training_id:s.id}));
 const applyLatest=(s:Session)=>{const latest=s.plan?.latest;if(!latest||latest.version<=Number(s.plan?.version??0))return;if(confirm(`Aplicar v${latest.version} apenas a esta sessão?`))router.post(route('desportivo.treinos.sessions.plan-version',s.id),{season_id:activeSeason?.id,training_plan_version_id:latest.id,reason:`Atualização explícita de v${s.plan?.version??'?'} para v${latest.version} em Treinos.`},{preserveScroll:true});};
 const submitCancel=()=>{if(!selected||!cancelReason.trim())return;router.post(route('desportivo.treinos.sessions.cancel',selected.id),{season_id:activeSeason?.id,reason:cancelReason},{preserveScroll:true,onSuccess:()=>{setCancelOpen(false);setCancelReason('')}})};
 const startAdapt=(s:Session)=>{setSelectedId(s.id);setEditBlocks(toEdit(s.blocks));setAdaptReason('');setAdaptOpen(true)};
 const patchBlock=(key:string,patch:Partial<EditBlock>)=>setEditBlocks(rows=>rows.map(b=>b.key===key?{...b,...patch}:b));
 const patchLine=(bk:string,lk:string,patch:Partial<EditLine>)=>setEditBlocks(rows=>rows.map(b=>b.key!==bk?b:{...b,series:b.series.map(l=>l.key===lk?{...l,...patch}:l)}));
 const submitAdapt=()=>{if(!selected||!adaptReason.trim())return;const blocks=editBlocks.map(b=>({name:b.name,rounds:Math.max(1,Number(b.rounds)||1),series:b.series.map(l=>({repeticoes:Math.max(1,Number(l.repeticoes)||1),distancia_m:Number(l.distancia_m)||0,exercicio:l.exercicio||null,intervalo:l.intervalo||null,saida:l.saida||null,timing_mode:l.timing_mode,training_zone_config_id:l.training_zone_config_id||null,sports_stroke_id:l.sports_stroke_id||null,zona_intensidade:l.zona_intensidade||null,estilo:l.estilo||null,material_ids:l.material.map(m=>m.id).filter((id):id is string=>!!id),material:l.material,observacoes:l.observacoes||null}))}));router.put(route('desportivo.treinos.sessions.snapshot',selected.id),{season_id:activeSeason?.id,reason:adaptReason,blocks},{preserveScroll:true,onSuccess:()=>{setAdaptOpen(false);setAdaptReason('')}})};
 return <AuthenticatedLayout fullWidth header={<div className="flex w-full items-center justify-between gap-4"><div><h1 className="text-lg font-semibold sm:text-xl">Desportivo</h1><p className="text-xs text-muted-foreground">Preparação e operação das sessões concretas</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.estrutura.index'))}><Buildings size={16} className="mr-1"/>Estrutura</Button><Button size="icon" variant="outline" onClick={()=>router.get(route('desportivo.configuracao.index'))}><GearSix size={17}/></Button></div></div>}>
  <Head title="Desportivo · Treinos"/>
  <div className="flex min-h-0 flex-1 flex-col gap-3 overflow-hidden">
   <div className="grid shrink-0 grid-cols-4 gap-1 rounded-lg border bg-background p-1 sm:grid-cols-8">{nav.map(([key,label,Icon,url])=><button key={key} onClick={()=>key!=='treinos'&&router.get(url())} className={`flex items-center justify-center gap-1 rounded-md px-2 py-1.5 text-xs ${key==='treinos'?'bg-muted font-medium':'text-muted-foreground hover:bg-muted/60'}`}><Icon size={12}/>{label}</button>)}</div>
   <div className="flex shrink-0 flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-base font-semibold">Treinos</h2><p className="text-xs text-muted-foreground">Prontidão, conteúdo aplicado, recursos, alterações e passagem ao Cais.</p></div><div className="flex gap-2">{activeSeason&&<Badge variant="outline">{activeSeason.name} · {activeSeason.year}</Badge>}<Button size="sm" onClick={()=>goPlanning()}>+ Nova sessão no Planeamento</Button></div></div>
   <div className="grid shrink-0 grid-cols-2 gap-2 xl:grid-cols-4">{[['Sessões hoje',stats.today],['Precisam de atenção',stats.attention],['Decisões pendentes',stats.decisions],['Próximos 7 dias',stats.next7days]].map(([label,value])=><Card key={String(label)}><CardContent className="p-3"><b className="block text-xl">{value}</b><span className="text-[11px] text-muted-foreground">{label}</span></CardContent></Card>)}</div>
   <div className="flex shrink-0 flex-col gap-2 xl:flex-row"><Input className="h-9 xl:max-w-md" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pesquisar treino, grupo, treinador, plano, local…"/><Select value={status} onValueChange={setStatus}><SelectTrigger className="h-9 xl:w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os estados</SelectItem><SelectItem value="published">Publicados</SelectItem><SelectItem value="draft">Rascunhos</SelectItem><SelectItem value="completed">Concluídos</SelectItem><SelectItem value="cancelled">Cancelados</SelectItem></SelectContent></Select><Select value={ready} onValueChange={setReady}><SelectTrigger className="h-9 xl:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Toda a prontidão</SelectItem><SelectItem value="ready">Prontos</SelectItem><SelectItem value="attention">Atenção</SelectItem><SelectItem value="decision">Decisão</SelectItem><SelectItem value="closed">Fechados</SelectItem></SelectContent></Select><Select value={group} onValueChange={setGroup}><SelectTrigger className="h-9 xl:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os grupos</SelectItem>{groups.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={coach} onValueChange={setCoach}><SelectTrigger className="h-9 xl:w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todos os treinadores</SelectItem>{coaches.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><div className="flex gap-1 xl:ml-auto"><Button size="sm" variant={view==='list'?'default':'outline'} onClick={()=>setView('list')}>Lista</Button><Button size="sm" variant={view==='cards'?'default':'outline'} onClick={()=>setView('cards')}>Cards</Button></div></div>
   <div className="min-h-0 flex-1 overflow-y-auto">{view==='list'?<Card><CardContent className="overflow-x-auto p-0"><table className="w-full min-w-[1080px] text-xs"><thead className="sticky top-0 border-b bg-background"><tr>{['Data / sessão','Grupos','Conteúdo','Local','Treinador','Prontidão','Estado',''].map(h=><th key={h} className="px-3 py-2 text-left font-medium text-muted-foreground">{h}</th>)}</tr></thead><tbody>{filtered.map(s=><tr key={s.id} className="border-b last:border-0 hover:bg-muted/30"><td className="px-3 py-2.5"><button className="font-semibold hover:underline" onClick={()=>{setSelectedId(s.id);setTab('summary')}}>{dateLabel(s.date)} · {timeRange(s)}</button><div className="text-[11px] text-muted-foreground">{s.number||'Sessão'}{s.periodization.micro?` · ${s.periodization.micro}`:''}</div></td><td className="px-3 py-2.5"><b>{s.groups.map(g=>g.group_name).filter(Boolean).join(', ')||'Sem grupo'}</b><div className="text-[11px] text-muted-foreground">{s.athletes.length} atleta(s)</div></td><td className="px-3 py-2.5"><b>{s.plan?`${s.plan.name} · v${s.plan.version}`:(s.training_type||'Conteúdo manual')}</b><div className="text-[11px] text-muted-foreground">{s.volume_m.toLocaleString('pt-PT')} m{s.content_overridden?' · adaptado':''}</div></td><td className="px-3 py-2.5">{s.location.venue||'—'}<div className="text-[11px] text-muted-foreground">{s.location.pool||'sem piscina/área'}</div></td><td className="px-3 py-2.5">{s.coach?.name||'—'}</td><td className="px-3 py-2.5"><Badge variant={readyVariant(s.readiness.status)}>{readyLabel(s.readiness.status)}</Badge></td><td className="px-3 py-2.5"><Badge variant={s.status==='cancelled'?'destructive':s.status==='completed'?'secondary':'outline'}>{statusLabel(s.status)}</Badge></td><td className="px-3 py-2.5"><Button size="sm" className="h-7" onClick={()=>{setSelectedId(s.id);setTab('summary')}}>Abrir</Button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-6 text-center text-xs text-muted-foreground">Nenhuma sessão corresponde aos filtros.</p>}</CardContent></Card>:<div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{filtered.map(s=><Card key={s.id} className="cursor-pointer hover:shadow-sm" onClick={()=>{setSelectedId(s.id);setTab('summary')}}><CardContent className="p-3"><div className="flex justify-between"><b>{dateLabel(s.date)} · {timeRange(s)}</b><Badge variant={readyVariant(s.readiness.status)}>{readyLabel(s.readiness.status)}</Badge></div><p className="mt-1 text-xs">{s.groups.map(g=>g.group_name).filter(Boolean).join(', ')||'Sem grupo'}</p><p className="text-[11px] text-muted-foreground">{s.plan?`${s.plan.name} v${s.plan.version}`:(s.training_type||'Conteúdo manual')} · {s.volume_m.toLocaleString('pt-PT')} m</p></CardContent></Card>)}</div>}</div>
  </div>
  <Dialog open={!!selected} onOpenChange={v=>!v&&setSelectedId(null)}><DialogContent className="h-[94vh] w-[97vw] max-w-[1400px] overflow-hidden p-0">{selected&&<><DialogHeader className="border-b px-4 py-3"><div className="flex justify-between gap-3"><div><DialogTitle>{selected.number||'Sessão'} · {selected.groups.map(g=>g.group_name).filter(Boolean).join(', ')||selected.training_type||'Treino'}</DialogTitle><div className="mt-1 flex gap-1"><Badge variant={selected.status==='cancelled'?'destructive':'outline'}>{statusLabel(selected.status)}</Badge><Badge variant={readyVariant(selected.readiness.status)}>{readyLabel(selected.readiness.status)}</Badge><Badge variant="outline">{dateLabel(selected.date)} · {timeRange(selected)}</Badge></div></div></div></DialogHeader><Tabs value={tab} onValueChange={setTab} className="flex min-h-0 flex-1 flex-col"><TabsList className="mx-4 mt-3 grid grid-cols-5"><TabsTrigger value="summary">Resumo</TabsTrigger><TabsTrigger value="content">Conteúdo</TabsTrigger><TabsTrigger value="people">Participantes</TabsTrigger><TabsTrigger value="resources">Recursos</TabsTrigger><TabsTrigger value="history">Histórico</TabsTrigger></TabsList><div className="min-h-0 flex-1 overflow-y-auto p-4">
   <TabsContent value="summary" className="mt-0 space-y-3"><div className="grid gap-3 lg:grid-cols-2"><Card><CardContent className="p-3"><b className="text-sm">Contexto</b><p className="mt-2 text-xs">{[selected.periodization.season,selected.periodization.macro,selected.periodization.meso,selected.periodization.micro].filter(Boolean).join(' → ')||'Sem contexto de periodização'}</p></CardContent></Card><Card><CardContent className="p-3"><b className="text-sm">Sessão</b><p className="mt-2 text-xs">{selected.coach?.name||'Sem treinador'} · {selected.location.venue||'Sem local'} · {selected.location.pool||'Sem piscina/área'}</p></CardContent></Card></div><Card><CardContent className="p-3"><b className="text-sm">Prontidão operacional</b><div className="mt-2 grid gap-2 sm:grid-cols-2">{selected.readiness.checks.map(c=><div key={c.key} className="rounded-md border p-2"><div className="flex justify-between"><b className="text-xs">{c.label}</b><Badge variant={c.status==='decision'?'destructive':c.status==='ok'?'default':'outline'}>{c.status==='ok'?'OK':c.status==='decision'?'Decisão':'Atenção'}</Badge></div><p className="mt-1 text-[11px] text-muted-foreground">{c.message}</p></div>)}</div></CardContent></Card>{selected.cancellation&&<Card><CardContent className="p-3"><b>Cancelamento</b><p className="text-xs">{selected.cancellation.reason}</p></CardContent></Card>}</TabsContent>
   <TabsContent value="content" className="mt-0 space-y-2"><Card><CardContent className="p-3"><div className="flex justify-between gap-2"><div><b>{selected.plan?`${selected.plan.name} · v${selected.plan.version}`:(selected.training_type||'Snapshot manual')}</b><p className="text-[11px] text-muted-foreground">{selected.volume_m.toLocaleString('pt-PT')} m{selected.content_overridden?' · adaptação desta sessão':''}</p></div>{!['cancelled','completed'].includes(selected.status)&&<div className="flex gap-1">{selected.plan?.latest&&selected.plan.latest.version>selected.plan.version&&<Button size="sm" variant="outline" onClick={()=>applyLatest(selected)}>Aplicar v{selected.plan.latest.version}</Button>}<Button size="sm" variant="outline" onClick={()=>startAdapt(selected)}>Adaptar esta sessão</Button></div>}</div></CardContent></Card>{selected.blocks.map((b,i)=><Card key={`${b.name}-${i}`}><CardContent className="p-0"><div className="border-b bg-muted/20 px-3 py-2"><b className="text-xs">{b.name}{b.rounds>1?` · ${b.rounds} rondas`:''}</b></div>{b.series.map(l=><div key={l.id} className="grid grid-cols-[75px_1fr_70px_90px] gap-2 border-b px-3 py-2 text-xs last:border-0"><b>{l.repeticoes}×{l.distancia_m}</b><span>{l.exercicio||l.estilo||'—'}</span><span>{l.zona||'—'}</span><span>{l.saida?`@${l.saida}`:l.intervalo?`c/${l.intervalo}`:'—'}</span></div>)}</CardContent></Card>)}</TabsContent>
   <TabsContent value="people" className="mt-0 grid gap-3 lg:grid-cols-2"><Card><CardContent className="p-3"><b>Grupos</b><div className="mt-2 space-y-2">{selected.groups.map(g=><div key={g.id} className="rounded border p-2 text-xs"><b>{g.group_name||'Grupo'}</b><p className="text-[11px] text-muted-foreground">{g.plan?`${g.plan.name} v${g.plan.version}`:(g.instruction||'Conteúdo global')}</p></div>)}</div></CardContent></Card><Card><CardContent className="p-3"><b>Atletas preparados · {selected.athletes.length}</b><div className="mt-2 max-h-[420px] overflow-auto">{selected.athletes.map(a=><div key={a.id} className="border-b py-1.5 text-xs">{a.name}</div>)}</div><p className="mt-2 text-[11px] text-muted-foreground">A assiduidade é registada no Cais.</p></CardContent></Card></TabsContent>
   <TabsContent value="resources" className="mt-0 space-y-3"><div className="grid gap-3 lg:grid-cols-2"><Card><CardContent className="p-3"><b>Local</b><p className="mt-2 text-xs">{selected.location.venue||'—'} · {selected.location.pool||'—'}</p></CardContent></Card><Card><CardContent className="p-3"><b>Pistas</b><div className="mt-2 space-y-2">{selected.groups.map(g=><div key={g.id} className="text-xs"><b>{g.group_name}</b><div className="mt-1 flex gap-1">{g.lanes.map(l=><Badge key={l.id} variant="outline">Pista {l.number??l.name}</Badge>)}</div></div>)}</div></CardContent></Card></div><Card><CardContent className="p-3"><b>Material técnico previsto</b><div className="mt-2 flex flex-wrap gap-1">{Array.from(new Set(selected.blocks.flatMap(b=>b.series.flatMap(l=>l.material.map(m=>m.name).filter(Boolean) as string[])))).map(v=><Badge key={v} variant="outline">{v}</Badge>)}</div><p className="mt-2 text-[11px] text-muted-foreground">O stock continua a pertencer à Logística.</p></CardContent></Card></TabsContent>
   <TabsContent value="history" className="mt-0"><Card><CardContent className="p-3"><b>Linha temporal</b><div className="mt-3 space-y-3">{selected.history.map((e,i)=><div key={`${e.type}-${e.at}-${i}`} className="border-l-2 pl-3"><b className="text-xs">{e.title}</b><p className="text-[11px] text-muted-foreground">{e.detail||'—'}</p><p className="text-[10px] text-muted-foreground">{e.at?new Date(e.at).toLocaleString('pt-PT'):'—'}{e.by?` · ${e.by}`:''}</p></div>)}</div></CardContent></Card></TabsContent>
  </div></Tabs><div className="flex shrink-0 flex-wrap justify-end gap-1 border-t p-3">{!['cancelled','completed'].includes(selected.status)&&<Button size="sm" variant="destructive" onClick={()=>{setCancelReason('');setCancelOpen(true)}}>Cancelar sessão</Button>}<Button size="sm" variant="outline" onClick={()=>goPlanning(selected)}>Editar planeamento</Button>{!['cancelled','completed'].includes(selected.status)&&<Button size="sm" onClick={()=>goCais(selected)}>Abrir no Cais</Button>}</div></>}</DialogContent></Dialog>
  <Dialog open={cancelOpen} onOpenChange={setCancelOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Cancelar sessão</DialogTitle></DialogHeader><p className="text-xs text-muted-foreground">A sessão não é apagada; o histórico é preservado.</p><Label>Motivo obrigatório</Label><textarea className="min-h-24 rounded-md border bg-background p-2 text-sm" value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setCancelOpen(false)}>Voltar</Button><Button variant="destructive" disabled={!cancelReason.trim()} onClick={submitCancel}>Confirmar</Button></div></DialogContent></Dialog>
  <Dialog open={adaptOpen} onOpenChange={setAdaptOpen}><DialogContent className="h-[90vh] w-[96vw] max-w-[1100px] overflow-y-auto"><DialogHeader><DialogTitle>Adaptar snapshot desta sessão</DialogTitle></DialogHeader><p className="text-xs text-muted-foreground">Não modifica a Biblioteca; fica auditado apenas nesta ocorrência.</p><div><Label>Motivo obrigatório</Label><Input value={adaptReason} onChange={e=>setAdaptReason(e.target.value)}/></div><div className="space-y-2">{editBlocks.map(b=><Card key={b.key}><CardContent className="p-3"><div className="grid gap-2 sm:grid-cols-[1fr_90px]"><Input value={b.name} onChange={e=>patchBlock(b.key,{name:e.target.value})}/><Input type="number" min={1} value={b.rounds} onChange={e=>patchBlock(b.key,{rounds:e.target.value})}/></div><div className="mt-2 space-y-2">{b.series.map(l=><div key={l.key} className="grid gap-2 rounded border p-2 md:grid-cols-[70px_80px_1fr_120px]"><Input type="number" min={1} value={l.repeticoes} onChange={e=>patchLine(b.key,l.key,{repeticoes:e.target.value})}/><Input type="number" min={0} value={l.distancia_m} onChange={e=>patchLine(b.key,l.key,{distancia_m:e.target.value})}/><Input value={l.exercicio} onChange={e=>patchLine(b.key,l.key,{exercicio:e.target.value})}/><Select value={l.timing_mode} onValueChange={v=>patchLine(b.key,l.key,{timing_mode:v as EditLine['timing_mode']})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem tempo</SelectItem><SelectItem value="each_rep">Cada repetição</SelectItem><SelectItem value="whole_series">Série completa</SelectItem></SelectContent></Select><Input value={l.saida} onChange={e=>patchLine(b.key,l.key,{saida:e.target.value})} placeholder="Saída @"/><Input value={l.intervalo} onChange={e=>patchLine(b.key,l.key,{intervalo:e.target.value})} placeholder="Descanso"/></div>)}</div></CardContent></Card>)}</div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setAdaptOpen(false)}>Cancelar</Button><Button disabled={!adaptReason.trim()||!editBlocks.length} onClick={submitAdapt}>Guardar adaptação</Button></div></DialogContent></Dialog>
 </AuthenticatedLayout>;
}
