<?php

declare(strict_types=1);

return [
    'version' => 'M4.12',
    'fields' => [
        'arquivo_consentimento' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_configuracao',
            'canonical_field' => 'arquivo_consentimento',
            'reason' => 'Campo documental legado sem mapeamento fechado no fallback map; requer validacao de backfill e cobertura funcional.',
            'next_action' => 'Confirmar persistencia em dados_configuracao e validar uso em portal/admin antes de isolamento.',
        ],
        'arquivo_rgpd' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_configuracao',
            'canonical_field' => 'arquivo_rgpd',
            'reason' => 'Campo legado de comprovativo RGPD sem decisao final de retenção operacional.',
            'next_action' => 'Validar origem dos anexos e cobrir leitura canónica antes de qualquer isolamento.',
        ],
        'cartao_federacao' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'desportivo',
            'canonical_area' => 'dados_configuracao',
            'canonical_field' => 'cartao_federacao',
            'reason' => 'Campo documental/desportivo legacy sem fecho de cobertura canónica em toda a superficie.',
            'next_action' => 'Validar fluxos desportivos e portal para garantir que dados_configuracao cobre o campo.',
        ],
        'centro_custo' => [
            'decision' => 'keep_until_module_refactor',
            'risk' => 'high',
            'owner_area' => 'financeiro',
            'canonical_area' => 'financeiro',
            'canonical_field' => null,
            'reason' => 'Campo financeiro legacy com potencial acoplamento transversal; manter ate refatoracao dedicada.',
            'next_action' => 'Mapear dependencias reais em fluxos financeiros e definir destino canónico antes de isolamento.',
        ],
        'conta_corrente' => [
            'decision' => 'keep_until_module_refactor',
            'risk' => 'high',
            'owner_area' => 'financeiro',
            'canonical_area' => 'financeiro',
            'canonical_field' => null,
            'reason' => 'Campo financeiro legacy com historico e sem fonte unica equivalente para remocao imediata.',
            'next_action' => 'Concluir estrategia de normalizacao financeira e validar migração controlada antes de isolamento.',
        ],
        'contacto_emergencia_nome' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'contacto_emergencia_nome',
            'reason' => 'Campo pessoal sem mapeamento fechado no fallback map, mas com destino canónico esperado.',
            'next_action' => 'Validar cobertura completa do campo em dados_pessoais e confirmar leitura sem fallback legacy.',
        ],
        'contacto_emergencia_relacao' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'contacto_emergencia_relacao',
            'reason' => 'Campo pessoal sem decisao final de isolamento, dependente de validacao de backfill.',
            'next_action' => 'Confirmar consistencia em dados_pessoais e validacao funcional no portal/admin.',
        ],
        'contacto_emergencia_telefone' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'contacto_emergencia_telefone',
            'reason' => 'Campo pessoal sem mapeamento tecnico fechado, com destino canónico esperado.',
            'next_action' => 'Validar dados existentes e cobertura canónica antes de propor isolamento.',
        ],
        'data_atestado_medico' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'desportivo',
            'canonical_area' => 'dados_configuracao',
            'canonical_field' => 'data_atestado_medico',
            'reason' => 'Campo de configuracao/desportivo sem fecho formal de cobertura em todos os fluxos.',
            'next_action' => 'Confirmar leitura canónica em payloads desportivos e portal antes de isolamento.',
        ],
        'declaracao_transporte' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_configuracao',
            'canonical_field' => 'declaracao_transporte',
            'reason' => 'Campo de configuracao legacy com potencial duplicidade semantica e sem decisao final de retenção.',
            'next_action' => 'Validar coexistencia com declaracao_de_transporte e definir convergencia canónica.',
        ],
        'empresa' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'empresa',
            'reason' => 'Campo pessoal legacy sem mapeamento tecnico no fallback map, aguardando validacao de dados.',
            'next_action' => 'Confirmar preenchimento em dados_pessoais e uso real antes de decidir isolamento.',
        ],
        'escola' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'escola',
            'reason' => 'Campo pessoal sem cobertura explicita no mapa canónico de fallback.',
            'next_action' => 'Validar necessidade operacional e consolidacao em dados_pessoais.',
        ],
        'estado_civil' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'estado_civil',
            'reason' => 'Campo pessoal legacy com cobertura canónica implícita, sem validacao final de backfill.',
            'next_action' => 'Confirmar completude em dados_pessoais e revisar necessidade funcional.',
        ],
        'foto_perfil' => [
            'decision' => 'keep_historical_or_external_reference',
            'risk' => 'medium',
            'owner_area' => 'documentos',
            'canonical_area' => 'historico_ou_ficheiros',
            'canonical_field' => null,
            'reason' => 'Campo de ficheiro/historico pode ter referencia externa e requer estrategia de retenção.',
            'next_action' => 'Mapear armazenamento definitivo e politicas de arquivo antes de isolamento.',
        ],
        'informacoes_medicas' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'desportivo',
            'canonical_area' => 'dados_configuracao',
            'canonical_field' => 'informacoes_medicas',
            'reason' => 'Campo sensivel sem fechamento total de cobertura canónica no mapa tecnico atual.',
            'next_action' => 'Validar consistencia entre dados_configuracao e payloads desportivos.',
        ],
        'inscricao' => [
            'decision' => 'keep_until_module_refactor',
            'risk' => 'high',
            'owner_area' => 'financeiro',
            'canonical_area' => 'financeiro',
            'canonical_field' => null,
            'reason' => 'Campo financeiro com semantica historica e acoplamento intermodular; manter nesta fase.',
            'next_action' => 'Definir plano de substituicao no modulo financeiro antes de isolamento.',
        ],
        'numero_cartao_cidadao' => [
            'decision' => 'needs_business_decision',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'documento_identificacao',
            'reason' => 'Campo classificado como unknown_review; precisa validacao de origem e enquadramento documental antes de isolamento.',
            'next_action' => 'Validar se deve convergir para documento_identificacao e confirmar requisitos legais de retenção.',
        ],
        'numero_irmaos' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'numero_irmaos',
            'reason' => 'Campo pessoal legacy sem decisao final de retencao operacional.',
            'next_action' => 'Confirmar uso real e cobertura em dados_pessoais antes de isolamento.',
        ],
        'numero_utente' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'numero_utente',
            'reason' => 'Campo pessoal sem mapeamento tecnico fechado no fallback map.',
            'next_action' => 'Validar backfill e exigencias de uso no contexto operacional.',
        ],
        'ocupacao' => [
            'decision' => 'candidate_after_backfill_validation',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'ocupacao',
            'reason' => 'Campo pessoal legado com destino canónico provável, dependente de validacao.',
            'next_action' => 'Confirmar cobertura em dados_pessoais e necessidade funcional.',
        ],
        'telefone' => [
            'decision' => 'needs_business_decision',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'contacto',
            'reason' => 'Campo classificado como unknown_review; precisa validacao de origem e uso historico antes de isolamento.',
            'next_action' => 'Validar se duplica contacto/contacto_telefonico/telemovel ou se tem origem externa.',
        ],
        'tipo_mensalidade' => [
            'decision' => 'keep_until_module_refactor',
            'risk' => 'high',
            'owner_area' => 'financeiro',
            'canonical_area' => 'financeiro',
            'canonical_field' => null,
            'reason' => 'Campo financeiro legacy com dependencias historicas em fluxos de mensalidades.',
            'next_action' => 'Fechar convergencia para fonte canónica no financeiro antes de isolamento.',
        ],
        'validade_cartao_cidadao' => [
            'decision' => 'needs_business_decision',
            'risk' => 'medium',
            'owner_area' => 'membros',
            'canonical_area' => 'dados_pessoais',
            'canonical_field' => 'validade_documento',
            'reason' => 'Campo classificado como unknown_review; precisa validacao de semantica e obrigações de retenção.',
            'next_action' => 'Validar convergencia para validade_documento e confirmar ciclo de vida do dado.',
        ],
    ],
];
