<?php

declare(strict_types=1);

return [
    'version' => 'M6.0',
    'generated_context' => [
        'fallback_guard_required' => 'members:audit-data-fallback --fail-on-fallback',
        'structure_audit_required' => 'members:audit-data-structure',
        'notes' => 'Inventário documental/operacional. Não remove campos.',
    ],
    'categories' => [
        'auth_operational_keep' => [
            'description' => 'Campos necessários para autenticação, identidade operacional e compatibilidade Laravel.',
            'fields' => [
                'id',
                'name',
                'email',
                'email_verified_at',
                'password',
                'remember_token',
                'email_utilizador',
                'senha',
                'perfil',
                'estado',
                'numero_socio',
                'created_at',
                'updated_at',
            ],
        ],
        'member_personal_legacy' => [
            'description' => 'Campos pessoais legados que ainda não foram removidos do users.',
            'fields' => [
                'nome_completo',
                'data_nascimento',
                'sexo',
                'morada',
                'codigo_postal',
                'localidade',
                'contacto',
                'telemovel',
                'contacto_telefonico',
                'nif',
                'cc',
                'nacionalidade',
                'email_secundario',
                'ocupacao',
                'empresa',
                'escola',
                'numero_utente',
                'contacto_emergencia_nome',
                'contacto_emergencia_telefone',
                'contacto_emergencia_relacao',
            ],
        ],
        'removed_after_m5' => [
            'description' => 'Campos legacy removidos fisicamente de users na sprint M6 após readiness M5 validada.',
            'fields' => [
                'estado_civil',
                'numero_irmaos',
            ],
        ],
        'removed_after_fc2' => [
            'description' => 'Campos financeiros legacy removidos fisicamente de users na sprint FC2 após readiness FC1.1 validada.',
            'fields' => [
                'tipo_mensalidade',
                'conta_corrente',
                'centro_custo',
            ],
        ],
        'member_configuration_legacy' => [
            'description' => 'Campos de configuração e consentimento legados em users.',
            'fields' => [
                'rgpd',
                'data_rgpd',
                'arquivo_rgpd',
                'consentimento',
                'data_consentimento',
                'arquivo_consentimento',
                'afiliacao',
                'data_afiliacao',
                'arquivo_afiliacao',
                'num_federacao',
                'cartao_federacao',
                'declaracao_de_transporte',
                'declaracao_transporte',
                'data_atestado_medico',
                'arquivo_atestado_medico',
                'informacoes_medicas',
            ],
        ],
        'member_financial_legacy' => [
            'description' => 'Campos financeiros legados ainda associados ao users (não removidos em FC2).',
            'fields' => [
                'inscricao',
            ],
        ],
        'sports_operational_keep' => [
            'description' => 'Campos desportivos operacionais que continuam a existir no users.',
            'fields' => [
                'ativo_desportivo',
                'escalao',
                'numero_pmb',
                'data_inscricao',
                'tipo_membro',
            ],
        ],
        'relationship_family_operational_keep' => [
            'description' => 'Campos operacionais para relações familiares e educação.',
            'fields' => [
                'menor',
                'encarregado_educacao',
                'educandos',
            ],
        ],
        'files_or_historical_review' => [
            'description' => 'Campos de ficheiros ou revisão histórica documental.',
            'fields' => [
                'foto_perfil',
            ],
        ],
        'unknown_review' => [
            'description' => 'Campos encontrados em migrations/schema/fillable que não estejam classificados acima.',
            'fields' => [
                'telefone',
                'numero_cartao_cidadao',
                'validade_cartao_cidadao',
            ],
        ],
    ],
    'field_to_category' => [
        'id' => 'auth_operational_keep',
        'name' => 'auth_operational_keep',
        'email' => 'auth_operational_keep',
        'email_verified_at' => 'auth_operational_keep',
        'password' => 'auth_operational_keep',
        'remember_token' => 'auth_operational_keep',
        'email_utilizador' => 'auth_operational_keep',
        'senha' => 'auth_operational_keep',
        'perfil' => 'auth_operational_keep',
        'estado' => 'auth_operational_keep',
        'numero_socio' => 'auth_operational_keep',
        'created_at' => 'auth_operational_keep',
        'updated_at' => 'auth_operational_keep',
        'nome_completo' => 'member_personal_legacy',
        'data_nascimento' => 'member_personal_legacy',
        'sexo' => 'member_personal_legacy',
        'morada' => 'member_personal_legacy',
        'codigo_postal' => 'member_personal_legacy',
        'localidade' => 'member_personal_legacy',
        'contacto' => 'member_personal_legacy',
        'telemovel' => 'member_personal_legacy',
        'contacto_telefonico' => 'member_personal_legacy',
        'nif' => 'member_personal_legacy',
        'cc' => 'member_personal_legacy',
        'nacionalidade' => 'member_personal_legacy',
        'email_secundario' => 'member_personal_legacy',
        'estado_civil' => 'removed_after_m5',
        'ocupacao' => 'member_personal_legacy',
        'empresa' => 'member_personal_legacy',
        'escola' => 'member_personal_legacy',
        'numero_irmaos' => 'removed_after_m5',
        'numero_utente' => 'member_personal_legacy',
        'contacto_emergencia_nome' => 'member_personal_legacy',
        'contacto_emergencia_telefone' => 'member_personal_legacy',
        'contacto_emergencia_relacao' => 'member_personal_legacy',
        'rgpd' => 'member_configuration_legacy',
        'data_rgpd' => 'member_configuration_legacy',
        'arquivo_rgpd' => 'member_configuration_legacy',
        'consentimento' => 'member_configuration_legacy',
        'data_consentimento' => 'member_configuration_legacy',
        'arquivo_consentimento' => 'member_configuration_legacy',
        'afiliacao' => 'member_configuration_legacy',
        'data_afiliacao' => 'member_configuration_legacy',
        'arquivo_afiliacao' => 'member_configuration_legacy',
        'num_federacao' => 'member_configuration_legacy',
        'cartao_federacao' => 'member_configuration_legacy',
        'declaracao_de_transporte' => 'member_configuration_legacy',
        'declaracao_transporte' => 'member_configuration_legacy',
        'data_atestado_medico' => 'member_configuration_legacy',
        'arquivo_atestado_medico' => 'member_configuration_legacy',
        'informacoes_medicas' => 'member_configuration_legacy',
        'tipo_mensalidade' => 'removed_after_fc2',
        'conta_corrente' => 'removed_after_fc2',
        'centro_custo' => 'removed_after_fc2',
        'inscricao' => 'member_financial_legacy',
        'ativo_desportivo' => 'sports_operational_keep',
        'escalao' => 'sports_operational_keep',
        'numero_pmb' => 'sports_operational_keep',
        'data_inscricao' => 'sports_operational_keep',
        'tipo_membro' => 'sports_operational_keep',
        'menor' => 'relationship_family_operational_keep',
        'encarregado_educacao' => 'relationship_family_operational_keep',
        'educandos' => 'relationship_family_operational_keep',
        'foto_perfil' => 'files_or_historical_review',
        'telefone' => 'unknown_review',
        'numero_cartao_cidadao' => 'unknown_review',
        'validade_cartao_cidadao' => 'unknown_review',
    ],
    'removal_prerequisites' => [
        'member_personal_legacy' => [
            'Confirmar ausência de fallback e leituras residuais em users.',
            'Validar que dados_pessoais cobre toda a superfície funcional.',
            'Atualizar imports, API, portal e auditorias dependentes.',
        ],
        'member_configuration_legacy' => [
            'Confirmar ausência de fallback e leituras residuais em users.',
            'Validar que dados_configuracao cobre toda a superfície funcional.',
            'Atualizar forms, serviços e relatórios dependentes.',
        ],
        'removed_after_m5' => [
            'Remoção física executada em M6 com migration destrutiva dedicada e rollback estrutural.',
            'Rollback recria apenas o schema em users; não repõe automaticamente os valores migrados.',
            'Manter auditorias de leitura/escrita legacy verdes após o drop físico.',
        ],
        'removed_after_fc2' => [
            'Remoção física executada em FC2 com migration destrutiva dedicada e rollback estrutural.',
            'Rollback recria apenas o schema em users; não repõe automaticamente os valores removidos.',
            'Backfills/auditorias devem operar em modo schema-aware quando as colunas já não existem.',
        ],
        'member_financial_legacy' => [
            'Confirmar substituição por tabelas financeiras canónicas.',
            'Validar impacto em PaymentAllocationService e fluxos de membro.',
            'Auditar integridade de conta_corrente e inscrição antes de remoção.',
        ],
        'sports_operational_keep' => [
            'Rever impacto no módulo desportivo e em relações de presença/treino.',
            'Garantir que o novo modelo operacional substitui o campo legacy.',
        ],
        'relationship_family_operational_keep' => [
            'Convergir relações familiares para o modelo canónico definido na sprint dedicada.',
            'Validar leitura e navegação no portal família antes de qualquer remoção.',
        ],
        'files_or_historical_review' => [
            'Confirmar se o ficheiro continua necessário para histórico ou migração.',
            'Garantir substituição por media/documents antes da remoção.',
        ],
        'unknown_review' => [
            'Rever origem no schema, fillable e migrations antes de qualquer decisão.',
            'Classificar em categoria funcional apropriada ou justificar manutenção.',
        ],
    ],
];