import {useEffect,useMemo,useState} from'react';
import{Head,router}from'@inertiajs/react';
import axios from'axios';
import AuthenticatedLayout from'@/Layouts/AuthenticatedLayout';
import{Badge}from'@/Components/ui/badge';
import{Button}from'@/Components/ui/button';
import{Card,CardContent,CardHeader,CardTitle}from'@/Components/ui/card';
import{Input}from'@/Components/ui/input';

type Athlete={id:string;name:string;member_number?:string;groups:{id:string;name:string}[]};
type Group={id:string;name:string;modality?:string;athlete_count:number};
type Competition={id:string;name:string;starts_at?:string;location?:string;status:string};
type Indicator={code:string;name:string;source:string;nature:string};
type MetricRow={code:string;name:string;unit?:string|null;count:number;latest?:string|number|null;latest_number?:number|null;average?:number|null};
type AnalysisResult={id:string;competition_id:string;competition:string;date?:string|null;race_id:string;race:string;distance_m:number;official_time:number|null;position?:number|null;points?:number|null;status:string;splits:{distance_m:number;time:number}[]};
type AthleteDetail={athlete:Athlete;window:any;kpis:any;training:{scheduled_rows:number;present:number;late:number;absent:number;volume_m:number;avg_rpe:number|null;rpe_coverage:number|null;weekly:any[];cais_metrics:MetricRow[];live_metrics:MetricRow[]};evaluations:any[];results:AnalysisResult[];results_by_race:any[];relationships:any;coverage:any;disclaimer:string};
type Props={athletes:Athlete[];groups:Group[];competitions:Competition[];windows:number[];indicators:Indicator[];principles:any};
type View='athlete'|'group'|'competition'|'indicators';type Tab='summary'|'training'|'evaluations'|'results'|'relationships';
const fmt=(v?:number|null,d=1)=>v==null?'—':Number(v).toFixed(d);const km=(v?:number|null)=>v==null?'—':`${(v/1000).toFixed(1)} km`;const time=(s?:number|null)=>{if(s==null)return'—';const m=Math.floor(s/60),r=s-m*60;return m?`${m}:${r.toFixed(2).padStart(5,'0')}`:r.toFixed(2)};
export default function AnalysisWorkspace({athletes,groups,competitions,windows,indicators,principles}:Props){
 const[view,setView]=useState<View>('athlete'),[athleteId,setAthleteId]=useState(athletes[0]?.id??''),[groupId,setGroupId]=useState(groups[0]?.id??''),[competitionId,setCompetitionId]=useState(competitions[0]?.id??''),[weeks,setWeeks]=useState(12),[tab,setTab]=useState<Tab>('summary'),[query,setQuery]=useState(''),[groupFilter,setGroupFilter]=useState('all'),[detail,setDetail]=useState<AthleteDetail|null>(null),[groupDetail,setGroupDetail]=useState<any>(null),[competitionDetail,setCompetitionDetail]=useState<any>(null);
 const filtered=useMemo(()=>{const needle=query.trim().toLowerCase();return athletes.filter(a=>(groupFilter==='all'||a.groups.some(g=>g.id===groupFilter))&&(!needle||a.name.toLowerCase().includes(needle)||(a.member_number??'').toLowerCase().includes(needle)))},[athletes,query,groupFilter]);
 useEffect(()=>{if(athleteId)axios.get(route('desportivo.analise.athlete',{athlete:athleteId}),{params:{weeks}}).then(r=>setDetail(r.data))},[athleteId,weeks]);
 useEffect(()=>{if(view==='group'&&groupId)axios.get(route('desportivo.analise.group',{group:groupId}),{params:{weeks}}).then(r=>setGroupDetail(r.data))},[view,groupId,weeks]);
 useEffect(()=>{if(view==='competition'&&competitionId)axios.get(route('desportivo.analise.competition',{competition:competitionId})).then(r=>setCompetitionDetail(r.data))},[view,competitionId]);
 const exportAthlete=()=>{if(!athleteId)return;window.location.assign(route('desportivo.analise.athlete.export',{athlete:athleteId,weeks}))};
 return <AuthenticatedLayout fullWidth><Head title="Análise · Desportivo"/><div className="mx-auto max-w-[1500px] space-y-3 p-3">
 <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-lg font-semibold">Análise</h1><p className="text-xs text-muted-foreground">Interpretação transversal de treino, avaliações e competição</p></div><div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'))}>Registos</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.avaliacoes.index'))}>Avaliações</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.resultados'))}>Resultados</Button>{view==='athlete'&&athleteId&&<Button size="sm" onClick={exportAthlete}>Exportar análise</Button>}</div></div>
 <div className="flex gap-1 overflow-auto">{([['athlete','Por atleta'],['group','Por grupo'],['competition','Competição'],['indicators','Indicadores']]as const).map(([k,l])=><Button key={k} size="sm" variant={view===k?'default':'outline'} onClick={()=>setView(k)}>{l}</Button>)}</div>
 {view==='athlete'&&<><div className="grid gap-2 md:grid-cols-[2fr_1fr_1fr]"><Input placeholder="Pesquisar atleta ou n.º de sócio…" value={query} onChange={e=>setQuery(e.target.value)}/><select className="h-9 rounded border bg-background px-2 text-xs" value={groupFilter} onChange={e=>setGroupFilter(e.target.value)}><option value="all">Todos os grupos</option>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select className="h-9 rounded border bg-background px-2 text-xs" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}>{windows.map(w=><option key={w} value={w}>{w} semanas</option>)}</select></div><div className="grid gap-3 lg:grid-cols-[330px_1fr]"><Card><CardHeader><CardTitle className="text-sm">Atletas <span className="font-normal text-muted-foreground">({filtered.length})</span></CardTitle></CardHeader><CardContent className="space-y-2">{filtered.map(a=><button key={a.id} type="button" onClick={()=>setAthleteId(a.id)} className={`w-full rounded-lg border p-3 text-left ${athleteId===a.id?'border-sky-300 bg-sky-50':''}`}><div className="flex items-center justify-between gap-2"><b className="text-xs">{a.name}</b>{a.member_number&&<span className="text-[10px] text-muted-foreground">#{a.member_number}</span>}</div><p className="text-[10px] text-muted-foreground">{a.groups.map(g=>g.name).join(' · ')||'Sem grupo atual'}</p></button>)}</CardContent></Card><Card><CardHeader><div className="flex justify-between"><CardTitle className="text-sm">{detail?.athlete.name??'Seleciona um atleta'}</CardTitle>{detail&&<Badge variant="outline">Cobertura {detail.coverage.score}%</Badge>}</div></CardHeader><CardContent>{detail&&<><div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-5"><K n={detail.kpis.attendance_rate==null?'—':`${detail.kpis.attendance_rate}%`} l="Assiduidade"/><K n={km(detail.kpis.volume_m)} l="Volume"/><K n={fmt(detail.kpis.avg_rpe)} l="RPE médio"/><K n={fmt(detail.kpis.evaluation_average)} l="Avaliação média"/><K n={detail.kpis.podiums} l="Pódios"/></div><div className="mb-3 flex gap-1 overflow-auto">{([['summary','Resumo'],['training','Treino'],['evaluations','Avaliações'],['results','Resultados'],['relationships','Relações']]as const).map(([k,l])=><Button key={k} size="sm" variant={tab===k?'default':'outline'} onClick={()=>setTab(k)}>{l}</Button>)}</div><AthleteBody tab={tab} d={detail}/><p className="mt-3 rounded border bg-muted/30 p-2 text-[10px] text-muted-foreground">{detail.disclaimer}</p></>}</CardContent></Card></div></>}
 {view==='group'&&<><div className="flex gap-2"><select className="h-9 flex-1 rounded border bg-background px-2 text-xs" value={groupId} onChange={e=>setGroupId(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><select className="h-9 rounded border bg-background px-2 text-xs" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}>{windows.map(w=><option key={w} value={w}>{w} semanas</option>)}</select></div>{groupDetail&&<Card><CardHeader><CardTitle className="text-sm">{groupDetail.group.name}</CardTitle></CardHeader><CardContent><div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-6"><K n={groupDetail.athlete_count} l="Atletas"/><K n={groupDetail.attendance_average==null?'—':`${groupDetail.attendance_average}%`} l="Assiduidade média"/><K n={km(groupDetail.volume_total_m)} l="Volume total"/><K n={fmt(groupDetail.rpe_average)} l="RPE médio"/><K n={fmt(groupDetail.evaluation_average)} l="Avaliação média"/><K n={groupDetail.podiums} l="Pódios"/></div><div className="space-y-1">{groupDetail.athletes.map((a:any)=><div key={a.id} className="grid gap-2 rounded border p-2 text-xs md:grid-cols-6"><b>{a.name}</b><span>{a.attendance_rate==null?'—':`${a.attendance_rate}%`}</span><span>{km(a.volume_m)}</span><span>RPE {fmt(a.avg_rpe)}</span><span>Aval. {fmt(a.evaluation_average)}</span><span>Cobertura {a.coverage}%</span></div>)}</div></CardContent></Card>}</>}
 {view==='competition'&&<><select className="h-9 w-full rounded border bg-background px-2 text-xs" value={competitionId} onChange={e=>setCompetitionId(e.target.value)}>{competitions.map(c=><option key={c.id} value={c.id}>{c.name} · {c.starts_at}</option>)}</select>{competitionDetail&&<Card><CardHeader><CardTitle className="text-sm">{competitionDetail.competition.name}</CardTitle></CardHeader><CardContent><div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-7"><K n={competitionDetail.stats.results} l="Resultados"/><K n={competitionDetail.stats.athletes} l="Atletas"/><K n={competitionDetail.stats.podiums} l="Pódios"/><K n={competitionDetail.stats.dsq} l="DSQ"/><K n={competitionDetail.stats.dns} l="DNS"/><K n={competitionDetail.stats.dnf} l="DNF"/><K n={competitionDetail.stats.points} l="Pontos"/></div><div className="space-y-1">{competitionDetail.races.map((r:any)=><div key={r.id} className="flex flex-wrap justify-between gap-2 rounded border p-2 text-xs"><b>{r.label}</b><span>{r.results} resultados · {r.podiums} pódios · melhor {time(r.best_time)}</span></div>)}</div></CardContent></Card>}</>}
 {view==='indicators'&&<Card><CardHeader><CardTitle className="text-sm">Indicadores e proveniência</CardTitle></CardHeader><CardContent className="space-y-2"><div className="rounded border bg-sky-50 p-3 text-xs">Análise é read-only. O KeyValue legacy de Performance não é fonte ativa: <b>{String(principles.legacy_performance_kv_active)}</b>.</div>{indicators.map(i=><div key={i.code} className="grid gap-2 rounded border p-3 text-xs md:grid-cols-3"><b>{i.name}</b><span>{i.source}</span><Badge variant="outline" className="w-fit">{i.nature}</Badge></div>)}</CardContent></Card>}
 </div></AuthenticatedLayout>}
function K({n,l}:{n:string|number;l:string}){return <div className="rounded border p-2"><b className="block text-base">{n}</b><span className="text-[10px] text-muted-foreground">{l}</span></div>}
function AthleteBody({tab,d}:{tab:Tab;d:AthleteDetail}){if(tab==='summary')return <div className="grid gap-2 md:grid-cols-2"><section className="rounded border p-3 text-xs"><b>Qualidade dos dados</b><p className="mt-2">Treinos: {d.coverage.training_rows}</p><p>RPE: {d.coverage.rpe_rows}</p><p>Métricas Cais: {d.coverage.cais_metrics}</p><p>Métricas Live: {d.coverage.live_metrics}</p><p>Avaliações: {d.coverage.evaluations}</p><p>Resultados: {d.coverage.results}</p></section><section className="rounded border p-3 text-xs"><b>Últimas semanas</b>{d.training.weekly.slice(-6).map((w:any)=><div key={w.week} className="mt-2 flex justify-between border-t pt-2"><span>{w.week}</span><span>{km(w.volume_m)} · RPE {fmt(w.avg_rpe)}</span></div>)}</section></div>;if(tab==='training')return <div className="space-y-3"><div className="grid gap-2 md:grid-cols-4"><K n={d.training.present} l="Presentes"/><K n={d.training.late} l="Atrasos"/><K n={d.training.absent} l="Ausências"/><K n={d.training.rpe_coverage==null?'—':`${d.training.rpe_coverage}%`} l="Cobertura RPE"/></div><MetricList title="Métricas Cais" rows={d.training.cais_metrics}/><MetricList title="Métricas Live" rows={d.training.live_metrics}/></div>;if(tab==='evaluations')return <div className="space-y-2">{d.evaluations.length===0&&<Empty text="Sem avaliações concluídas nesta janela."/>}{d.evaluations.map(e=><div key={e.id} className="rounded border p-3 text-xs"><div className="flex justify-between"><b>{e.campaign}</b><span>{e.score??'—'}</span></div>{e.summary&&<p className="mt-1 text-muted-foreground">{e.summary}</p>}</div>)}</div>;if(tab==='results')return <ResultsAnalysis d={d}/>;return <div className="rounded border p-3 text-xs"><b>Treino semanal vs. resultado competitivo</b><p className="mt-1 text-muted-foreground">{d.relationships.interpretation}</p><p className="mt-1 text-[10px] text-muted-foreground">Amostra comparável: {d.relationships.sample_size}</p><div className="mt-2 space-y-1">{d.relationships.weekly_training_vs_result.map((x:any)=><div key={`${x.week}-${x.race}`} className="flex flex-wrap justify-between gap-2 border-t py-2"><span>{x.week} · {x.race}</span><span>{km(x.volume_m)} · RPE {fmt(x.avg_rpe)} · {time(x.result_time)}</span></div>)}</div></div>}
function MetricList({title,rows}:{title:string;rows:MetricRow[]}){return <section className="rounded border"><div className="border-b bg-muted/30 px-3 py-2 text-xs font-semibold">{title}</div><div className="space-y-1 p-2">{rows.length===0&&<Empty text={`Sem ${title.toLowerCase()} registadas nesta janela.`}/>} {rows.map(m=><div key={m.code} className="flex flex-wrap justify-between gap-2 rounded border p-2 text-xs"><b>{m.name}</b><span>{m.latest??'—'}{m.unit?` ${m.unit}`:''}{m.average!=null?` · média ${fmt(m.average,2)}`:''} · n={m.count}</span></div>)}</div></section>}
function ResultsAnalysis({d}:{d:AthleteDetail}){const[openId,setOpenId]=useState<string|null>(null);return <div className="space-y-3"><section className="space-y-2">{d.results_by_race.length===0&&<Empty text="Sem resultados competitivos nesta janela."/>}{d.results_by_race.map(r=><div key={r.race} className="grid gap-2 rounded border p-2 text-xs md:grid-cols-4"><b>{r.race}</b><span>Melhor {time(r.best_time)}</span><span>{r.participations} participações</span><span>{r.podiums} pódios</span></div>)}</section><section className="rounded border"><div className="border-b bg-muted/30 px-3 py-2 text-xs font-semibold">Resultados e splits</div><div className="divide-y">{d.results.map(r=><div key={r.id}><button type="button" onClick={()=>setOpenId(openId===r.id?null:r.id)} className="grid w-full gap-2 p-3 text-left text-xs md:grid-cols-[1.3fr_1fr_100px_80px_100px]"><span><b>{r.competition}</b><span className="block text-[10px] text-muted-foreground">{r.date??'—'}</span></span><span>{r.race}</span><span>{r.status==='ok'?time(r.official_time):r.status.toUpperCase()}</span><span>#{r.position??'—'}</span><span>{r.splits.length>0?`${r.splits.length} splits`:'Sem splits'}</span></button>{openId===r.id&&<div className="bg-muted/20 px-3 pb-3"><div className="flex flex-wrap gap-2">{r.splits.length===0?<span className="text-[10px] text-muted-foreground">Sem parciais registados.</span>:r.splits.map(s=><Badge key={`${r.id}-${s.distance_m}`} variant="outline">{s.distance_m}m · {time(s.time)}</Badge>)}</div></div>}</div>)}</div></section></div>}
function Empty({text}:{text:string}){return <p className="p-2 text-xs text-muted-foreground">{text}</p>}
