import { useEffect, useMemo, useState } from 'react';
import { Head, router } from '@inertiajs/react';
import axios from 'axios';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/Components/ui/dialog';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';

type Row={id:string;name:string;location?:string;starts_at?:string;ends_at?:string;type?:string;status:string;projection_status?:string;race_count:number;result_count:number;registration_count:number;financial_amount:number;readiness:{state:string;issues:string[]}};
type Props={competitions:Row[];filters:Record<string,string|null>;status_options:string[];type_options:string[]};
type Detail={competition:any;projection:any;program:any[];convocations:any[];registrations:any[];finance:any;results:any[];team_results:any[];readiness:{state:string;issues:string[]}};
type WorkspaceView='competitions'|'calendar'|'entries'|'results';
type DetailTab='summary'|'program'|'callups'|'entries'|'finance'|'results';

const fmt=(v?:string)=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-PT'):'—';
const euro=(v:number)=>new Intl.NumberFormat('pt-PT',{style:'currency',currency:'EUR'}).format(v||0);

export default function CompetitionsWorkspace({competitions,filters,status_options,type_options}:Props){
 const [view,setView]=useState<WorkspaceView>('competitions');
 const [selectedId,setSelectedId]=useState(competitions[0]?.id??'');
 const [detail,setDetail]=useState<Detail|null>(null);
 const [tab,setTab]=useState<DetailTab>('summary');
 const [search,setSearch]=useState(filters.search??'');
 const [competitionOpen,setCompetitionOpen]=useState(false);
 const [competitionDraft,setCompetitionDraft]=useState({name:'',starts_at:new Date().toISOString().slice(0,10),ends_at:'',location:'',type:'prova'});
 const [raceOpen,setRaceOpen]=useState(false);
 const [raceDraft,setRaceDraft]=useState({distance_m:'100',stroke:'Livre',gender:'M',order:'1'});
 const selected=useMemo(()=>competitions.find(c=>c.id===selectedId)??competitions[0],[competitions,selectedId]);
 const calendar=useMemo(()=>[...competitions].sort((a,b)=>(a.starts_at??'').localeCompare(b.starts_at??'')),[competitions]);
 useEffect(()=>{if(!selected?.id){setDetail(null);return}axios.get<Detail>(route('desportivo.competicoes.show',{competition:selected.id})).then(r=>setDetail(r.data));},[selected?.id]);
 const refreshDetail=async()=>{if(!selected)return;const {data}=await axios.get<Detail>(route('desportivo.competicoes.show',{competition:selected.id}));setDetail(data)};
 const apply=()=>router.get(route('desportivo.competicoes'),{search:search||undefined,status:filters.status||undefined,type:filters.type||undefined},{preserveState:false});
 const createCompetition=async()=>{if(!competitionDraft.name||!competitionDraft.starts_at)return;await axios.post('/api/desportivo/competitions',{nome:competitionDraft.name,data_inicio:competitionDraft.starts_at,data_fim:competitionDraft.ends_at||null,local:competitionDraft.location||'N/A',tipo_prova:competitionDraft.type||'prova'});setCompetitionOpen(false);router.reload();};
 const editCompetition=async()=>{if(!selected||!detail)return;setCompetitionDraft({name:detail.competition.name,starts_at:detail.competition.starts_at??'',ends_at:detail.competition.ends_at??'',location:detail.competition.location??'',type:detail.competition.type??'prova'});setCompetitionOpen(true)};
 const saveCompetition=async()=>{if(!selected)return createCompetition();await axios.put(`/api/desportivo/competitions/${selected.id}`,{nome:competitionDraft.name,data_inicio:competitionDraft.starts_at,data_fim:competitionDraft.ends_at||null,local:competitionDraft.location||'N/A',tipo_prova:competitionDraft.type||'prova'});setCompetitionOpen(false);router.reload();};
 const openNewCompetition=()=>{setSelectedId('');setCompetitionDraft({name:'',starts_at:new Date().toISOString().slice(0,10),ends_at:'',location:'',type:'prova'});setCompetitionOpen(true)};
 const openRace=()=>{setRaceDraft({distance_m:'100',stroke:'Livre',gender:'M',order:String((detail?.program.length??0)+1)});setRaceOpen(true)};
 const addRace=async()=>{if(!selected)return;await axios.post('/api/provas',{competicao_id:selected.id,distancia_m:Number(raceDraft.distance_m),estilo:raceDraft.stroke,genero:raceDraft.gender,ordem_prova:Number(raceDraft.order)});setRaceOpen(false);await refreshDetail()};
 const deleteRace=async(id:string)=>{if(!window.confirm('Apagar esta prova do programa?'))return;await axios.delete(`/api/provas/${id}`);await refreshDetail()};
 return <AuthenticatedLayout fullWidth><Head title="Competições · Desportivo"/><div className="mx-auto max-w-[1500px] space-y-3 p-3">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-lg font-semibold">Competições</h1><p className="text-xs text-muted-foreground">Ciclo competitivo, convocatórias, inscrições e resultados</p></div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.avaliacoes.index'))}>Avaliações</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'))}>Registos</Button><Button size="sm" onClick={openNewCompetition}>+ Competição</Button></div></div>
  <div className="flex gap-1 overflow-auto">{([['competitions','Competições'],['calendar','Calendário'],['entries','Inscrições'],['results','Resultados']] as const).map(([k,l])=><Button key={k} size="sm" variant={view===k?'default':'outline'} onClick={()=>setView(k)}>{l}</Button>)}</div>
  {view==='competitions'&&<><div className="grid gap-2 md:grid-cols-[2fr_1fr_1fr_auto]"><Input placeholder="Pesquisar competição…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&apply()}/><select className="h-9 rounded-md border bg-background px-2 text-xs" defaultValue={filters.status??''} onChange={e=>router.get(route('desportivo.competicoes'),{search,status:e.target.value||undefined,type:filters.type||undefined})}><option value="">Todos os estados</option>{status_options.map(x=><option key={x}>{x}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-xs" defaultValue={filters.type??''} onChange={e=>router.get(route('desportivo.competicoes'),{search,status:filters.status||undefined,type:e.target.value||undefined})}><option value="">Todos os tipos</option>{type_options.map(x=><option key={x}>{x}</option>)}</select><Button size="sm" onClick={apply}>Aplicar</Button></div><div className="grid gap-3 lg:grid-cols-[360px_1fr]">
   <Card><CardHeader><CardTitle className="text-sm">Competições</CardTitle></CardHeader><CardContent className="space-y-2">{competitions.map(c=><button key={c.id} onClick={()=>setSelectedId(c.id)} className={`w-full rounded-lg border p-3 text-left ${selected?.id===c.id?'border-sky-300 bg-sky-50':''}`}><div className="flex items-start justify-between gap-2"><b className="text-xs">{c.name}</b><Badge variant="outline">{c.status}</Badge></div><div className="mt-1 text-[10px] text-muted-foreground">{fmt(c.starts_at)} · {c.location||'—'} · {c.type||'—'}</div><div className="mt-2 flex flex-wrap gap-1"><Badge variant="secondary">{c.race_count} provas</Badge><Badge variant="secondary">{c.registration_count} inscrições</Badge><Badge variant={c.readiness.state==='ready'?'default':'outline'}>{c.readiness.state}</Badge></div></button>)}</CardContent></Card>
   <Card><CardHeader className="pb-2"><div className="flex flex-wrap items-start justify-between gap-2"><div><CardTitle className="text-sm">{selected?.name??'Seleciona uma competição'}</CardTitle>{selected&&<p className="text-[10px] text-muted-foreground">{fmt(selected.starts_at)} · {selected.location}</p>}</div><div className="flex gap-1">{selected&&<Button size="sm" variant="outline" onClick={()=>void editCompetition()}>Editar</Button>}{detail?.projection&&<Badge variant={detail.projection.status==='linked'?'default':'outline'}>Evento: {detail.projection.status||'sem projeção'}</Badge>}</div></div></CardHeader><CardContent>{selected&&<><div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-5"><Kpi n={detail?.convocations.flatMap(x=>x.athletes).length??0} label="Convocados"/><Kpi n={detail?.registrations.length??0} label="Inscrições"/><Kpi n={detail?.program.length??0} label="Provas"/><Kpi n={detail?.results.length??0} label="Resultados"/><Kpi n={euro(selected.financial_amount)} label="Encargos"/></div><div className="mb-3 flex gap-1 overflow-auto">{([['summary','Resumo'],['program','Programa'],['callups','Convocatória'],['entries','Inscrições'],['finance','Financeiro'],['results','Resultados']] as const).map(([k,l])=><Button key={k} size="sm" variant={tab===k?'default':'outline'} onClick={()=>setTab(k)}>{l}</Button>)}</div>{!detail?<div className="rounded-lg border p-8 text-center text-xs text-muted-foreground">A carregar…</div>:<DetailView tab={tab} detail={detail} addRace={openRace} deleteRace={id=>void deleteRace(id)}/>}</>}</CardContent></Card>
  </div></>}
  {view==='calendar'&&<Card><CardHeader><CardTitle className="text-sm">Calendário competitivo</CardTitle></CardHeader><CardContent className="space-y-2">{calendar.map(c=><button key={c.id} className="flex w-full items-center justify-between rounded-lg border p-3 text-left" onClick={()=>{setSelectedId(c.id);setView('competitions')}}><div><b className="text-xs">{c.name}</b><p className="text-[10px] text-muted-foreground">{fmt(c.starts_at)}{c.ends_at&&c.ends_at!==c.starts_at?` – ${fmt(c.ends_at)}`:''} · {c.location}</p></div><Badge variant="outline">{c.status}</Badge></button>)}</CardContent></Card>}
  {view==='entries'&&<Card><CardHeader><CardTitle className="text-sm">Inscrições por competição</CardTitle></CardHeader><CardContent className="space-y-2">{competitions.map(c=><button key={c.id} className="flex w-full justify-between rounded-lg border p-3 text-left" onClick={()=>{setSelectedId(c.id);setTab('entries');setView('competitions')}}><div><b className="text-xs">{c.name}</b><p className="text-[10px] text-muted-foreground">{fmt(c.starts_at)} · {c.race_count} provas</p></div><Badge variant="secondary">{c.registration_count} inscrições</Badge></button>)}</CardContent></Card>}
  {view==='results'&&<Card><CardHeader><CardTitle className="text-sm">Resultados por competição</CardTitle></CardHeader><CardContent className="space-y-2">{competitions.map(c=><button key={c.id} className="flex w-full justify-between rounded-lg border p-3 text-left" onClick={()=>{setSelectedId(c.id);setTab('results');setView('competitions')}}><div><b className="text-xs">{c.name}</b><p className="text-[10px] text-muted-foreground">{fmt(c.starts_at)} · {c.location}</p></div><Badge variant="secondary">{c.result_count} resultados</Badge></button>)}</CardContent></Card>}
 </div>
 <Dialog open={competitionOpen} onOpenChange={setCompetitionOpen}><DialogContent><DialogHeader><DialogTitle>{selected?'Editar competição':'Nova competição'}</DialogTitle></DialogHeader><div className="grid gap-3"><div><Label>Nome</Label><Input value={competitionDraft.name} onChange={e=>setCompetitionDraft(v=>({...v,name:e.target.value}))}/></div><div className="grid grid-cols-2 gap-2"><div><Label>Início</Label><Input type="date" value={competitionDraft.starts_at} onChange={e=>setCompetitionDraft(v=>({...v,starts_at:e.target.value}))}/></div><div><Label>Fim</Label><Input type="date" value={competitionDraft.ends_at} onChange={e=>setCompetitionDraft(v=>({...v,ends_at:e.target.value}))}/></div></div><div><Label>Local</Label><Input value={competitionDraft.location} onChange={e=>setCompetitionDraft(v=>({...v,location:e.target.value}))}/></div><div><Label>Tipo</Label><Input value={competitionDraft.type} onChange={e=>setCompetitionDraft(v=>({...v,type:e.target.value}))}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setCompetitionOpen(false)}>Cancelar</Button><Button onClick={()=>void saveCompetition()}>Guardar</Button></DialogFooter></DialogContent></Dialog>
 <Dialog open={raceOpen} onOpenChange={setRaceOpen}><DialogContent><DialogHeader><DialogTitle>Adicionar prova</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><div><Label>Distância</Label><Input type="number" value={raceDraft.distance_m} onChange={e=>setRaceDraft(v=>({...v,distance_m:e.target.value}))}/></div><div><Label>Estilo</Label><Input value={raceDraft.stroke} onChange={e=>setRaceDraft(v=>({...v,stroke:e.target.value}))}/></div><div><Label>Género</Label><select className="h-9 w-full rounded-md border bg-background px-2" value={raceDraft.gender} onChange={e=>setRaceDraft(v=>({...v,gender:e.target.value}))}><option>M</option><option>F</option><option>MISTO</option></select></div><div><Label>Ordem</Label><Input type="number" value={raceDraft.order} onChange={e=>setRaceDraft(v=>({...v,order:e.target.value}))}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setRaceOpen(false)}>Cancelar</Button><Button onClick={()=>void addRace()}>Adicionar</Button></DialogFooter></DialogContent></Dialog>
 </AuthenticatedLayout>;
}

function Kpi({n,label}:{n:string|number;label:string}){return <div className="rounded-lg border p-2"><b className="block text-base">{n}</b><span className="text-[10px] text-muted-foreground">{label}</span></div>}
function DetailView({tab,detail,addRace,deleteRace}:{tab:DetailTab;detail:Detail;addRace:()=>void;deleteRace:(id:string)=>void}){
 if(tab==='summary')return <div className="grid gap-2 md:grid-cols-2"><section className="rounded-lg border p-3"><b className="text-xs">Dados competitivos</b><p className="mt-2 text-xs">Estado: {detail.competition.status}</p><p className="text-xs">Tipo: {detail.competition.type||'—'}</p><p className="text-xs">Evento projetado: {detail.projection.event_id||'—'}</p></section><section className="rounded-lg border p-3"><b className="text-xs">Prontidão</b><p className="mt-2 text-xs">{detail.readiness.state}</p>{detail.readiness.issues.map(x=><p key={x} className="text-xs text-amber-700">• {x}</p>)}</section></div>;
 if(tab==='program')return <section className="rounded-lg border"><div className="flex justify-between border-b p-3"><b className="text-xs">Programa de provas</b><Button size="sm" onClick={addRace}>+ Prova</Button></div>{detail.program.map(r=><div key={r.id} className="flex items-center justify-between border-b p-3 last:border-0"><div><b className="text-xs">#{r.order??'—'} · {r.distance_m} {r.stroke}</b><p className="text-[10px] text-muted-foreground">{r.gender} · {r.registrations} inscritos · {r.results} resultados</p></div><Button size="sm" variant="outline" onClick={()=>deleteRace(r.id)}>Apagar</Button></div>)}</section>;
 if(tab==='callups')return <section className="rounded-lg border"><div className="border-b p-3"><b className="text-xs">Convocatória ligada ao Evento projetado</b></div>{detail.convocations.length===0?<p className="p-3 text-xs text-muted-foreground">Ainda não existe convocatória para o Evento desta competição.</p>:detail.convocations.map(g=><div key={g.id} className="p-3"><div className="mb-2 flex justify-between"><b className="text-xs">Convocatória</b><Badge variant="outline">{g.publication_status}</Badge></div>{g.athletes.map((a:any)=><div key={a.user_id} className="flex justify-between border-t py-2 text-xs"><span>{a.name}</span><span>{a.confirmed?'Confirmado':'A aguardar'}</span></div>)}</div>)}</section>;
 if(tab==='entries')return <section className="rounded-lg border">{detail.registrations.length===0?<p className="p-3 text-xs text-muted-foreground">Sem inscrições.</p>:detail.registrations.map(r=><div key={r.id} className="flex justify-between border-b p-3 text-xs last:border-0"><div><b>{r.athlete}</b><p className="text-[10px] text-muted-foreground">{r.race}</p></div><span>{r.state} · {euro(r.amount)}</span></div>)}</section>;
 if(tab==='finance')return <div className="grid gap-2 md:grid-cols-2"><section className="rounded-lg border p-3"><b className="text-xs">Política financeira</b>{detail.finance.policy?<><p className="mt-2 text-xs">Pagador: {detail.finance.policy.payer_mode}</p><p className="text-xs">Cobrança: {detail.finance.policy.charge_mode}</p><p className="text-xs">Por prova: {detail.finance.policy.per_race_amount??'—'}</p><p className="text-xs">Centro de custo: {detail.finance.policy.cost_center??'—'}</p></>:<p className="mt-2 text-xs">Sem política.</p>}</section><section className="rounded-lg border p-3"><b className="text-xs">Obrigações</b><p className="mt-2 text-xs">{detail.finance.obligations.length} atleta(s) com obrigação financeira.</p></section></div>;
 return <section className="rounded-lg border">{detail.results.length===0?<p className="p-3 text-xs text-muted-foreground">Sem resultados registados.</p>:detail.results.map(r=><div key={r.id} className="flex justify-between border-b p-3 text-xs last:border-0"><span>{r.race}</span><span>{r.official_time??'—'} · {r.position?`${r.position}.º`:''}</span></div>)}</section>;
}
