import { Suspense, lazy, useEffect, useState } from 'react';
import { Head, router, usePage } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { moduleScrollableContentClass, moduleTabbedContentClass, moduleTabsClass, moduleViewportClass } from '@/lib/module-layout';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/Components/ui/tabs';
import { Buildings, Books, CalendarBlank, ChartBar, CheckSquare, GearSix, Lightning, MapTrifold, Trophy, UsersThree } from '@phosphor-icons/react';
import type { AgeGroup, AthleteOperationalRow, Competition, Event, EventResult, Macrocycle, MesocyclePlan, PresenceRow, Season, Stats, TeamResult, Training, User } from '@/types/sports';
import type { TrainingLibraryOption, TrainingLibraryPlan } from '@/components/sports/tabs/TrainingLibraryTab';

interface Props {
  tab?: string; stats?: Stats; alerts?: Array<{title:string;message:string;type:string}>; upcomingCompetitions?: Array<{id:string;nome:string;data_inicio:string;num_atletas_inscritos:number}>;
  seasons?: Season[]; selectedSeason?: Season|null; macrocycles?: Macrocycle[]; macrocycleOptions?: Array<{id:string;nome:string;epoca_id?:string}>; mesocycles?: MesocyclePlan[]; mesocycleOptions?: Array<{id:string;nome:string;macrociclo_id?:string;epoca_id?:string}>;
  microcycles?: Array<{id:string;nome:string;mesociclo_id?:string;macrocycle_id?:string;epoca_id?:string}>; microcycleOptions?: Array<{id:string;nome:string;mesociclo_id?:string;macrocycle_id?:string;epoca_id?:string}>; ageGroups?: AgeGroup[];
  trainingTypeOptions?: Array<{id:string;nome:string}>; trainingZoneOptions?: Array<{id:string;codigo:string;nome:string}>; trainings?: {data:Training[]}; calendarTrainings?: Array<{id:string;numero_treino?:string|null;data:string;macrocycle_id?:string|null;mesociclo_id?:string|null;microciclo_id?:string|null}>;
  trainingOptions?: Array<{id:string;numero_treino?:string|null;data:string}>; selectedTraining?: Training|null; presences?: PresenceRow[]; competitions?: Competition[]; results?: EventResult[]; teamResults?: TeamResult[]; users?: User[]; eventos?: Event[];
  costCenters?: Array<{id:string;nome:string;codigo?:string;ativo?:boolean}>; eventTypes?: Array<{id:string;nome:string;visibilidade_default?:string;ativo?:boolean}>; convocations?: any[]; convocationGroups?: any[]; provaTipos?: Array<{id:string;nome:string}>;
  statusOptions?: string[]; classificacaoOptions?: string[]; volumeByAthlete?: Array<{nome_completo:string;total_m:number}>; athleteOperationalRows?: AthleteOperationalRow[];
  libraryPlans?: TrainingLibraryPlan[]; libraryModalities?: TrainingLibraryOption[]; libraryTrainingTypes?: TrainingLibraryOption[]; libraryZones?: TrainingLibraryOption[]; libraryStrokes?: TrainingLibraryOption[]; libraryMaterials?: TrainingLibraryOption[];
}
type PageProps = Props & Record<string,unknown>;

const DashboardTab=lazy(()=>import('@/components/sports/tabs/DashboardTab').then(m=>({default:m.DashboardTab})));
const AthletesTab=lazy(()=>import('@/components/sports/tabs/AthletesTab').then(m=>({default:m.AthletesTab})));
const PlanningTab=lazy(()=>import('@/components/sports/tabs/PlanningTab').then(m=>({default:m.PlanningTab})));
const TrainingLibraryTab=lazy(()=>import('@/components/sports/tabs/TrainingLibraryTab').then(m=>({default:m.TrainingLibraryTab})));
const TrainingsTab=lazy(()=>import('@/components/sports/tabs/TrainingsTab').then(m=>({default:m.TrainingsTab})));
const PoolDeckTab=lazy(()=>import('@/components/sports/tabs/PoolDeckTab').then(m=>({default:m.PoolDeckTab})));
const CompetitionsTab=lazy(()=>import('@/components/sports/tabs/CompetitionsTab').then(m=>({default:m.CompetitionsTab})));
const PerformanceTab=lazy(()=>import('@/components/sports/tabs/PerformanceTab').then(m=>({default:m.PerformanceTab})));
const TABS=[['dashboard','Dashboard',ChartBar],['atletas','Atletas',UsersThree],['planeamento','Planeamento',MapTrifold],['biblioteca','Biblioteca',Books],['treinos','Treinos',CalendarBlank],['cais','Cais',CheckSquare],['competicoes','Competições',Trophy],['performance','Performance',Lightning]] as const;
type TabValue=(typeof TABS)[number][0];
const ROUTES:Record<TabValue,()=>string>={dashboard:()=>route('desportivo.index'),atletas:()=>route('desportivo.index',{tab:'atletas'}),planeamento:()=>route('desportivo.planeamento'),biblioteca:()=>route('desportivo.biblioteca'),treinos:()=>route('desportivo.treinos'),cais:()=>route('desportivo.cais'),competicoes:()=>route('desportivo.competicoes'),performance:()=>route('desportivo.relatorios')};
const DEFAULT_STATS:Stats={athletesCount:0,trainings7Days:0,trainings30Days:0,km7Days:0,km30Days:0};
const Loading=()=> <div className={moduleScrollableContentClass}><div className="min-h-[240px] rounded-lg border border-dashed border-border bg-background"/></div>;

export default function DesportivoIndex({tab='dashboard',stats=DEFAULT_STATS,alerts=[],upcomingCompetitions=[],seasons=[],selectedSeason=null,macrocycles=[],macrocycleOptions=[],mesocycles=[],mesocycleOptions=[],microcycles=[],microcycleOptions=[],ageGroups=[],trainingTypeOptions=[],trainingZoneOptions=[],trainings={data:[]},calendarTrainings=[],trainingOptions=[],selectedTraining=null,competitions=[],results=[],teamResults=[],users=[],eventos=[],costCenters=[],eventTypes=[],convocations=[],convocationGroups=[],provaTipos=[],volumeByAthlete=[],athleteOperationalRows=[],libraryPlans=[],libraryModalities=[],libraryTrainingTypes=[],libraryZones=[],libraryStrokes=[],libraryMaterials=[]}:Props){
  const page=usePage<PageProps>(); const initial=(tab==='presencas'?'cais':tab==='resultados'?'competicoes':tab) as TabValue; const active=TABS.some(([v])=>v===initial)?initial:'dashboard';
  const [toCais,setToCais]=useState(false); const [loadingVolume,setLoadingVolume]=useState(false); const hasVolume=Object.prototype.hasOwnProperty.call(page.props,'volumeByAthlete');
  const safeUsers=Array.isArray(users)?users:[]; const safeTrainings=Array.isArray(trainings?.data)?trainings.data:[]; const safeCompetitions=Array.isArray(competitions)?competitions:[]; const safeResults=Array.isArray(results)?results:[]; const safeVolume=Array.isArray(volumeByAthlete)?volumeByAthlete:[];
  useEffect(()=>{if(active!=='dashboard'||hasVolume||loadingVolume)return;setLoadingVolume(true);router.reload({only:['volumeByAthlete'],onFinish:()=>setLoadingVolume(false)})},[active,hasVolume,loadingVolume]);
  const resolvedTrainingOptions=trainingOptions.length?trainingOptions:safeTrainings.map(t=>({id:t.id,numero_treino:t.numero_treino??null,data:t.data??''}));
  const resolvedTypes=trainingTypeOptions.length?trainingTypeOptions:Array.from(new Set(safeTrainings.map(t=>t.tipo_treino).filter(Boolean))).map((nome,i)=>({id:`fallback-${i}`,nome}));
  const navigate=(value:string)=>{const t=value as TabValue;if(t===active)return;setToCais(t==='cais');router.get(ROUTES[t](),{},{preserveScroll:true,preserveState:false})};
  return <AuthenticatedLayout fullWidth header={<div className="flex w-full items-center justify-between gap-4"><div><h1 className="text-lg font-semibold tracking-tight sm:text-xl">Desportivo</h1><p className="mt-0.5 text-xs text-muted-foreground">Sistema técnico de gestão desportiva: planeamento, biblioteca, sessões, cais, competições e performance</p></div><div className="flex items-center gap-2"><button type="button" className="inline-flex h-9 items-center gap-2 rounded-md border bg-background px-3 text-xs font-medium text-muted-foreground hover:bg-muted hover:text-foreground" onClick={()=>router.get(route('desportivo.estrutura.index'))}><Buildings size={17}/><span className="hidden sm:inline">Estrutura</span></button><button type="button" className="inline-flex h-9 w-9 items-center justify-center rounded-md border bg-background text-muted-foreground hover:bg-muted hover:text-foreground" onClick={()=>router.get(route('desportivo.configuracao.index'))}><GearSix size={18}/></button></div></div>}>
    <Head title="Desportivo"/><div className={moduleViewportClass}>{toCais?<Loading/>:<Tabs value={active} onValueChange={navigate} className={moduleTabsClass}><TabsList className="grid h-auto w-full shrink-0 grid-cols-4 sm:grid-cols-8">{TABS.map(([value,label,Icon])=><TabsTrigger key={value} value={value} className="flex items-center gap-1.5 py-1.5 text-xs"><Icon size={12}/><span>{label}</span></TabsTrigger>)}</TabsList>
      <TabsContent value="dashboard" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><DashboardTab stats={stats} alerts={alerts} trainings={safeTrainings} upcomingCompetitions={upcomingCompetitions} competitions={safeCompetitions} eventos={eventos} ageGroups={ageGroups} users={safeUsers} volumeByAthlete={safeVolume}/></Suspense></TabsContent>
      <TabsContent value="atletas" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><AthletesTab users={safeUsers} volumeByAthlete={safeVolume} athleteOperationalRows={athleteOperationalRows} ageGroups={ageGroups}/></Suspense></TabsContent>
      <TabsContent value="planeamento" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><PlanningTab seasons={seasons} macrocycles={macrocycles} mesocycles={mesocycles} selectedSeasonId={selectedSeason?.id??null}/></Suspense></TabsContent>
      <TabsContent value="biblioteca" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><TrainingLibraryTab plans={libraryPlans} modalities={libraryModalities} trainingTypes={libraryTrainingTypes} zones={libraryZones} strokes={libraryStrokes} materials={libraryMaterials}/></Suspense></TabsContent>
      <TabsContent value="treinos" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><TrainingsTab trainings={safeTrainings} seasons={seasons} ageGroups={ageGroups} users={safeUsers} trainingTypeOptions={resolvedTypes} trainingZoneOptions={trainingZoneOptions} selectedSeasonId={selectedSeason?.id} macrocycles={macrocycleOptions.length?macrocycleOptions:macrocycles} mesocycles={mesocycleOptions.length?mesocycleOptions:mesocycles} microcycles={microcycleOptions.length?microcycleOptions:microcycles} planningSeason={selectedSeason} planningMacrocycles={macrocycles} planningMesocycles={mesocycles} calendarTrainings={calendarTrainings}/></Suspense></TabsContent>
      <TabsContent value="cais" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><PoolDeckTab trainings={safeTrainings} trainingOptions={resolvedTrainingOptions} selectedTraining={selectedTraining} users={safeUsers} ageGroups={ageGroups}/></Suspense></TabsContent>
      <TabsContent value="competicoes" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><CompetitionsTab competitions={safeCompetitions} results={safeResults} teamResults={teamResults} users={safeUsers} eventos={eventos} ageGroups={ageGroups} costCenters={costCenters} eventTypes={eventTypes} convocations={convocations} convocationGroups={convocationGroups} provaTipos={provaTipos}/></Suspense></TabsContent>
      <TabsContent value="performance" className={moduleTabbedContentClass}><Suspense fallback={<Loading/>}><PerformanceTab users={safeUsers} volumeByAthlete={safeVolume}/></Suspense></TabsContent>
    </Tabs>}</div>
  </AuthenticatedLayout>;
}
