import { useState } from 'react';
import { Head, router } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';

type PageData<T>={data:T[];current_page:number;last_page:number;total:number};
type TrainingRow={id:string;number?:string|null;date?:string|null;start_time?:string|null;group?:string|null;volume_m:number;present_count:number;measurement_count:number;metric_count:number;operational_count:number};
type Detail={session:any;summary:any;execution:any[];metrics:any[];operational:{attendance:any[];registers:any[];occurrences:any[]}};
interface Props{view:'training'|'athlete'|'type';filters:any;trainings?:PageData<TrainingRow>|null;athletes?:PageData<any>|null;records?:PageData<any>|null}

const fmt=(ms:number|null|undefined)=>{if(ms==null)return '—';const m=Math.floor(ms/60000),s=Math.floor((ms%60000)/1000),cs=Math.floor((ms%1000)/10);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(cs).padStart(2,'0')}`};
const json=async(url:string)=>{const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Não foi possível carregar os registos.');return r.json()};

export default function RecordsWorkspace({view,filters,trainings,athletes,records}:Props){
 const [detail,setDetail]=useState<Detail|null>(null); const [tab,setTab]=useState<'summary'|'execution'|'metrics'|'operational'>('summary'); const [loading,setLoading]=useState(false);
 const navigate=(next:string)=>router.get(route('desportivo.registos.index'),{...filters,view:next},{preserveState:false});
 const openTraining=async(id:string)=>{setLoading(true);try{setDetail(await json(route('desportivo.registos.training',{training:id})));setTab('summary')}finally{setLoading(false)}};
 return <AuthenticatedLayout fullWidth><Head title="Registos · Desportivo"/><div className="mx-auto max-w-[1500px] space-y-3 p-3">
  <div className="flex items-center justify-between gap-2"><div><h1 className="text-lg font-semibold">Registos</h1><p className="text-xs text-muted-foreground">Arquivo histórico desportivo · consulta read-only</p></div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.live'))}>Live</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.cais'))}>Cais</Button></div></div>
  <div className="flex gap-1 overflow-x-auto">{[['training','Por treino'],['athlete','Por atleta'],['type','Por tipo de registo']].map(([key,label])=><Button key={key} size="sm" variant={view===key?'default':'outline'} onClick={()=>navigate(key)}>{label}</Button>)}</div>
  <Card><CardContent className="grid gap-2 p-3 md:grid-cols-4"><Input type="date" defaultValue={filters?.from??''} onChange={(e)=>filters.from=e.target.value}/><Input type="date" defaultValue={filters?.to??''} onChange={(e)=>filters.to=e.target.value}/><div className="md:col-span-2 flex justify-end gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'),{view})}>Limpar</Button><Button size="sm" onClick={()=>router.get(route('desportivo.registos.index'),{...filters,view})}>Aplicar filtros</Button></div></CardContent></Card>
  {view==='training'&&<div className="grid gap-3 lg:grid-cols-[360px_1fr]"><Card><CardHeader className="py-3"><CardTitle className="text-sm">Treinos · {trainings?.total??0}</CardTitle></CardHeader><CardContent className="space-y-2">{trainings?.data.map(t=><button key={t.id} onClick={()=>void openTraining(t.id)} className="w-full rounded-lg border p-3 text-left hover:bg-muted/30"><div className="flex justify-between gap-2"><strong className="text-xs">#{t.number??'—'} · {t.group||'Treino'}</strong><span className="text-[10px] text-muted-foreground">{t.volume_m.toLocaleString('pt-PT')} m</span></div><div className="mt-1 text-[10px] text-muted-foreground">{t.date} · {t.start_time}</div><div className="mt-2 flex flex-wrap gap-1"><Badge variant="outline">{t.present_count} presentes</Badge><Badge variant="outline">{t.measurement_count} medições</Badge><Badge variant="outline">{t.metric_count} métricas</Badge></div></button>)}</CardContent></Card>
   <Card><CardHeader className="py-3"><CardTitle className="text-sm">{loading?'A carregar…':detail?`Treino #${detail.session.number??'—'}`:'Seleciona um treino'}</CardTitle></CardHeader><CardContent>{detail&&<><div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-4"><div className="rounded-lg border p-2"><b>{detail.session.volume_m.toLocaleString('pt-PT')} m</b><span className="block text-[10px] text-muted-foreground">Volume</span></div><div className="rounded-lg border p-2"><b>{detail.summary.present_count}</b><span className="block text-[10px] text-muted-foreground">Presentes</span></div><div className="rounded-lg border p-2"><b>{detail.summary.measurement_count}</b><span className="block text-[10px] text-muted-foreground">Medições</span></div><div className="rounded-lg border p-2"><b>{detail.summary.metric_count}</b><span className="block text-[10px] text-muted-foreground">Métricas</span></div></div><div className="mb-3 flex gap-1 overflow-auto">{(['summary','execution','metrics','operational'] as const).map(k=><Button key={k} size="sm" variant={tab===k?'default':'outline'} onClick={()=>setTab(k)}>{k==='summary'?'Resumo':k==='execution'?'Execução':k==='metrics'?'Métricas':'Operacional'}</Button>)}</div>
    {tab==='summary'&&<div className="space-y-2 text-xs"><div className="rounded-lg border p-3"><b>{detail.session.date} · {detail.session.start_time}</b><p className="text-muted-foreground">{detail.session.group} · {detail.session.coach||'Sem treinador'} · {detail.session.venue||'Sem local'}</p></div></div>}
    {tab==='execution'&&<div className="space-y-2">{detail.execution.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><b className="text-xs">{r.athlete} · {r.distance_m} m {r.stroke??''}</b><Badge variant="outline">{r.measurement_type==='free'?'Livre':`Rep ${r.repetition}`}</Badge></div><div className="mt-2 flex flex-wrap gap-1">{r.splits.map((s:any)=><Badge key={s.sequence} variant="outline">S{s.sequence} {fmt(s.elapsed_ms)}</Badge>)}<Badge>{fmt(r.final_ms)}</Badge></div></div>)}</div>}
    {tab==='metrics'&&<div className="space-y-2">{detail.metrics.map(r=><div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.athlete} · {r.metric}: {r.value}{r.unit?` ${r.unit}`:''}</b><div className="text-[10px] text-muted-foreground">{r.recorded_at?new Date(r.recorded_at).toLocaleString('pt-PT'):''} · {r.exercise||'sem exercício'}</div>{r.note&&<div className="mt-1">{r.note}</div>}</div>)}</div>}
    {tab==='operational'&&<div className="space-y-2">{detail.operational.registers.map(r=><div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.athlete} · {r.code}</b><div>{r.value||r.note}</div></div>)}{detail.operational.occurrences.map(r=><div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.type}</b><div>{r.reason}</div></div>)}</div>}
   </>}</CardContent></Card></div>}
  {view==='athlete'&&<Card><CardHeader><CardTitle className="text-sm">Por atleta</CardTitle></CardHeader><CardContent><p className="text-xs text-muted-foreground">A lista de atletas com histórico será paginada no servidor; ao selecionar um atleta, a timeline é carregada pelo endpoint dedicado.</p><pre className="mt-3 overflow-auto rounded-lg bg-muted p-3 text-[10px]">{JSON.stringify(athletes?.data??[],null,2)}</pre></CardContent></Card>}
  {view==='type'&&<Card><CardHeader><CardTitle className="text-sm">Por tipo de registo</CardTitle></CardHeader><CardContent><div className="mb-2 flex gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'),{...filters,view:'type',record_type:'timing'})}>Tempos & splits</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'),{...filters,view:'type',record_type:'metric'})}>Métricas</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'),{...filters,view:'type',record_type:'operational'})}>Operacional</Button></div><pre className="overflow-auto rounded-lg bg-muted p-3 text-[10px]">{JSON.stringify(records?.data??[],null,2)}</pre></CardContent></Card>}
 </div></AuthenticatedLayout>;
}
