import { useState } from 'react';
import { Head, router } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Badge } from '@/Components/ui/badge';
import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';

type PageData<T>={data:T[];current_page:number;last_page:number;total:number};
type Opt={id:string;name:string;unit?:string|null};
type Filters={from?:string|null;to?:string|null;athlete_id?:string|null;group_id?:string|null;stroke_id?:string|null;distance_m?:number|null;zone_id?:string|null;metric_definition_id?:string|null;record_type?:string|null;measurement_type?:string|null};
type TrainingRow={id:string;number?:string|null;date?:string|null;start_time?:string|null;group?:string|null;training_type?:string|null;volume_m:number;present_count:number;measurement_count:number;metric_count:number;operational_count:number};
type AthleteRow={id:string;name:string;training_count:number;measurement_count:number;metric_count:number};
type Detail={session:any;summary:any;execution:any[];metrics:any[];operational:{attendance:any[];registers:any[];occurrences:any[]}};
type Timeline={data:any[];current_page:number;last_page:number;total:number};
interface Props{view:'training'|'athlete'|'type';filters:Filters;filterOptions:{athletes:Opt[];groups:Opt[];strokes:Opt[];zones:Opt[];metrics:Opt[];distances:number[];recordTypes:Array<{value:string;label:string}>;measurementTypes:Array<{value:string;label:string}>};trainings?:PageData<TrainingRow>|null;athletes?:PageData<AthleteRow>|null;records?:PageData<any>|null}

const fmt=(ms:number|null|undefined)=>{if(ms==null)return '—';const m=Math.floor(ms/60000),s=Math.floor((ms%60000)/1000),cs=Math.floor((ms%1000)/10);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(cs).padStart(2,'0')}`};
const getJson=async(url:string)=>{const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Não foi possível carregar os registos.');return r.json()};
const Select=({value,onChange,children}:{value?:string|number|null;onChange:(v:string)=>void;children:React.ReactNode})=><select className="h-9 rounded-md border bg-background px-2 text-xs" value={value??''} onChange={e=>onChange(e.target.value)}>{children}</select>;

export default function RecordsWorkspace({view,filters,filterOptions,trainings,athletes,records}:Props){
 const [query,setQuery]=useState<Filters>({...filters});
 const [detail,setDetail]=useState<Detail|null>(null); const [tab,setTab]=useState<'summary'|'execution'|'metrics'|'operational'>('summary'); const [loading,setLoading]=useState(false);
 const [selectedAthlete,setSelectedAthlete]=useState<AthleteRow|null>(null); const [timeline,setTimeline]=useState<Timeline|null>(null);
 const nav=(next:string,extra:Record<string,unknown>={})=>router.get(route('desportivo.registos.index'),{...query,view:next,...extra},{preserveState:false});
 const apply=()=>router.get(route('desportivo.registos.index'),{...query,view},{preserveState:false});
 const openTraining=async(id:string)=>{setLoading(true);try{setDetail(await getJson(route('desportivo.registos.training',{training:id})));setTab('summary')}finally{setLoading(false)}};
 const openAthlete=async(a:AthleteRow)=>{setSelectedAthlete(a);setLoading(true);try{const qs=new URLSearchParams();if(query.from)qs.set('from',query.from);if(query.to)qs.set('to',query.to);setTimeline(await getJson(`${route('desportivo.registos.athlete',{athlete:a.id})}?${qs}`))}finally{setLoading(false)}};
 const exportCsv=()=>{const qs=new URLSearchParams();Object.entries(query).forEach(([k,v])=>{if(v!==null&&v!==undefined&&v!=='')qs.set(k,String(v))});window.location.href=`${route('desportivo.registos.export')}?${qs.toString()}`};
 const recordType=query.record_type||filters.record_type||'timing';
 return <AuthenticatedLayout fullWidth><Head title="Registos · Desportivo"/><div className="mx-auto max-w-[1500px] space-y-3 p-3">
  <div className="flex items-center justify-between gap-2"><div><h1 className="text-lg font-semibold">Registos</h1><p className="text-xs text-muted-foreground">Histórico desportivo consolidado · consulta read-only</p></div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.live'))}>Live</Button><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.cais'))}>Cais</Button></div></div>
  <div className="flex gap-1 overflow-x-auto">{[['training','Por treino'],['athlete','Por atleta'],['type','Por tipo de registo']].map(([k,l])=><Button key={k} size="sm" variant={view===k?'default':'outline'} onClick={()=>nav(k)}>{l}</Button>)}</div>
  <Card><CardContent className="p-3"><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-6"><Input type="date" value={query.from??''} onChange={e=>setQuery(q=>({...q,from:e.target.value||null}))}/><Input type="date" value={query.to??''} onChange={e=>setQuery(q=>({...q,to:e.target.value||null}))}/><Select value={query.athlete_id} onChange={v=>setQuery(q=>({...q,athlete_id:v||null}))}><option value="">Todos os atletas</option>{filterOptions.athletes.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select><Select value={query.group_id} onChange={v=>setQuery(q=>({...q,group_id:v||null}))}><option value="">Todos os grupos</option>{filterOptions.groups.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select>{view==='type'&&recordType==='metric'?<Select value={query.metric_definition_id} onChange={v=>setQuery(q=>({...q,metric_definition_id:v||null}))}><option value="">Todas as métricas</option>{filterOptions.metrics.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select>:<Select value={query.stroke_id} onChange={v=>setQuery(q=>({...q,stroke_id:v||null}))}><option value="">Todos os estilos</option>{filterOptions.strokes.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</Select>}<Select value={query.distance_m} onChange={v=>setQuery(q=>({...q,distance_m:v?Number(v):null}))}><option value="">Todas as distâncias</option>{filterOptions.distances.map(d=><option key={d} value={d}>{d} m</option>)}</Select></div><div className="mt-2 flex justify-end gap-1"><Button size="sm" variant="outline" onClick={()=>router.get(route('desportivo.registos.index'),{view})}>Limpar</Button>{view==='type'&&<Button size="sm" variant="outline" onClick={exportCsv}>Exportar CSV</Button>}<Button size="sm" onClick={apply}>Aplicar</Button></div></CardContent></Card>

  {view==='training'&&<div className="grid gap-3 lg:grid-cols-[360px_1fr]"><Card><CardHeader className="py-3"><CardTitle className="text-sm">Treinos · {trainings?.total??0}</CardTitle></CardHeader><CardContent className="space-y-2">{trainings?.data.map(t=><button key={t.id} onClick={()=>void openTraining(t.id)} className="w-full rounded-lg border p-3 text-left hover:bg-muted/30"><div className="flex justify-between gap-2"><strong className="text-xs">#{t.number??'—'} · {t.group||t.training_type||'Treino'}</strong><span className="text-[10px] text-muted-foreground">{t.volume_m.toLocaleString('pt-PT')} m</span></div><div className="mt-1 text-[10px] text-muted-foreground">{t.date} · {t.start_time}</div><div className="mt-2 flex flex-wrap gap-1"><Badge variant="outline">{t.present_count} presentes</Badge><Badge variant="outline">{t.measurement_count} tempos</Badge><Badge variant="outline">{t.metric_count} métricas</Badge><Badge variant="outline">{t.operational_count} operacionais</Badge></div></button>)}</CardContent></Card>
   <Card><CardHeader className="py-3"><CardTitle className="text-sm">{loading?'A carregar…':detail?`Treino #${detail.session.number??'—'}`:'Seleciona um treino'}</CardTitle></CardHeader><CardContent>{detail&&<><div className="mb-3 grid grid-cols-2 gap-2 md:grid-cols-4">{[['Volume',`${detail.session.volume_m.toLocaleString('pt-PT')} m`],['Presentes',detail.summary.present_count],['Medições',detail.summary.measurement_count],['Métricas',detail.summary.metric_count]].map(([l,v])=><div key={String(l)} className="rounded-lg border p-2"><b>{v}</b><span className="block text-[10px] text-muted-foreground">{l}</span></div>)}</div><div className="mb-3 flex gap-1 overflow-auto">{(['summary','execution','metrics','operational'] as const).map(k=><Button key={k} size="sm" variant={tab===k?'default':'outline'} onClick={()=>setTab(k)}>{k==='summary'?'Resumo':k==='execution'?'Execução':k==='metrics'?'Métricas':'Operacional'}</Button>)}</div>
    {tab==='summary'&&<div className="rounded-lg border p-3 text-xs"><b>{detail.session.date} · {detail.session.start_time}</b><p className="text-muted-foreground">{detail.session.group||'Sem grupo'} · {detail.session.coach||'Sem treinador'} · {detail.session.venue||'Sem local'}{detail.session.pool?` · ${detail.session.pool}`:''}</p></div>}
    {tab==='execution'&&<div className="space-y-2">{detail.execution.length===0?<p className="text-xs text-muted-foreground">Sem medições consolidadas.</p>:detail.execution.map(r=><div key={r.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><b className="text-xs">{r.athlete} · {r.distance_m} m {r.stroke??''}</b><Badge variant="outline">{r.measurement_type==='free'?'Livre':`R${r.round} · Rep ${r.repetition}`}</Badge></div><div className="mt-2 flex flex-wrap gap-1">{r.splits.map((s:any)=><Badge key={s.sequence} variant="outline">S{s.sequence} {fmt(s.elapsed_ms)}</Badge>)}<Badge>Final {fmt(r.final_ms)}</Badge></div></div>)}</div>}
    {tab==='metrics'&&<div className="space-y-2">{detail.metrics.length===0?<p className="text-xs text-muted-foreground">Sem métricas.</p>:detail.metrics.map(r=><div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.athlete} · {r.metric}: {r.value}{r.unit?` ${r.unit}`:''}</b><div className="text-[10px] text-muted-foreground">{r.recorded_at?new Date(r.recorded_at).toLocaleString('pt-PT'):''} · {r.exercise||'sem exercício'}</div>{r.note&&<div className="mt-1">{r.note}</div>}</div>)}</div>}
    {tab==='operational'&&<div className="space-y-3"><div><div className="mb-1 text-xs font-semibold">Presenças</div><div className="flex flex-wrap gap-1">{detail.operational.attendance.map(r=><Badge key={r.athlete_id} variant="outline">{r.athlete} · {r.status}</Badge>)}</div></div>{detail.operational.registers.map(r=><div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.athlete} · {r.code}</b><div>{r.value||r.note||'—'}</div></div>)}{detail.operational.occurrences.map(r=><div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.type}</b><div>{r.reason}</div></div>)}</div>}</>}</CardContent></Card></div>}

  {view==='athlete'&&<div className="grid gap-3 lg:grid-cols-[340px_1fr]"><Card><CardHeader className="py-3"><CardTitle className="text-sm">Atletas · {athletes?.total??0}</CardTitle></CardHeader><CardContent className="space-y-2">{athletes?.data.map(a=><button key={a.id} onClick={()=>void openAthlete(a)} className={`w-full rounded-lg border p-3 text-left ${selectedAthlete?.id===a.id?'border-sky-300 bg-sky-50':''}`}><b className="text-xs">{a.name}</b><div className="mt-2 flex gap-1"><Badge variant="outline">{a.training_count} treinos</Badge><Badge variant="outline">{a.measurement_count} tempos</Badge><Badge variant="outline">{a.metric_count} métricas</Badge></div></button>)}</CardContent></Card><Card><CardHeader className="py-3"><CardTitle className="text-sm">{loading?'A carregar…':selectedAthlete?selectedAthlete.name:'Seleciona um atleta'}</CardTitle></CardHeader><CardContent className="space-y-2">{timeline?.data.map((item:any)=><div key={item.training.id} className="rounded-lg border p-3"><div className="flex justify-between"><b className="text-xs">{item.training.date} · #{item.training.number??'—'}</b><span className="text-[10px] text-muted-foreground">{item.training.group}</span></div><div className="mt-2 space-y-1">{item.execution_summary.map((e:any)=><div key={`${e.distance_m}-${e.stroke}`} className="text-xs">{e.distance_m} m {e.stroke} · melhor <b>{fmt(e.best_ms)}</b> · {e.count} reg.</div>)}</div><div className="mt-2 flex flex-wrap gap-1">{item.metrics.map((m:any)=><Badge key={m.name} variant="outline">{m.name}: {m.value}{m.unit?` ${m.unit}`:''}</Badge>)}</div></div>)}</CardContent></Card></div>}

  {view==='type'&&<Card><CardHeader className="py-3"><div className="flex flex-wrap items-center justify-between gap-2"><CardTitle className="text-sm">Arquivo transversal · {records?.total??0}</CardTitle><div className="flex gap-1">{filterOptions.recordTypes.map(t=><Button key={t.value} size="sm" variant={recordType===t.value?'default':'outline'} onClick={()=>nav('type',{record_type:t.value})}>{t.label}</Button>)}</div></div></CardHeader><CardContent className="space-y-2">{records?.data.map((r:any)=>recordType==='timing'?<div key={r.id} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><b className="text-xs">{r.athlete} · {r.distance_m} m {r.stroke}</b><Badge variant="outline">{r.measurement_type==='free'?'Livre':'Planeada'}</Badge></div><div className="text-[10px] text-muted-foreground">{r.training_date??''} · #{r.training_number??'—'} · {r.exercise||'sem exercício'}</div><div className="mt-2 flex gap-1">{r.splits?.map((s:any)=><Badge key={s.sequence} variant="outline">S{s.sequence} {fmt(s.elapsed_ms)}</Badge>)}<Badge>{fmt(r.final_ms)}</Badge></div></div>:recordType==='metric'?<div key={r.id} className="rounded-lg border p-3 text-xs"><b>{r.athlete} · {r.metric}: {r.value}{r.unit?` ${r.unit}`:''}</b><div className="text-[10px] text-muted-foreground">{r.recorded_at?new Date(r.recorded_at).toLocaleString('pt-PT'):''} · {r.exercise||'sem exercício'}</div>{r.note&&<div className="mt-1">{r.note}</div>}</div>:<div key={`${r.kind}-${r.id}`} className="rounded-lg border p-3 text-xs"><div className="flex justify-between"><b>{r.kind==='attendance'?'Presença':r.kind==='occurrence'?'Ocorrência':'Registo Cais'} · {r.code}</b><span className="text-[10px] text-muted-foreground">{r.recorded_at?new Date(r.recorded_at).toLocaleString('pt-PT'):''}</span></div><div>{r.value||r.note||'—'}</div></div>)}</CardContent></Card>}
 </div></AuthenticatedLayout>;
}
